### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - April 8, 2024

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#10002]
Follow on to https://github.com/apache/arrow-datafusion/issues/9899

**It would be great for other contributors to DataFusion who plan non trivial work could try to make them visible somehow as well** 🙏  (feel free to copy / modify the format)

## My Highlights from Last Week
* 37.0.0 was released  https://github.com/apache/arrow-datafusion/issues/9682 🚀 
* DataFusion WASM is becoming a thing @milenkovicm showed us how to make WASM UDFs https://github.com/apache/arrow-datafusion/issues/9326 /  https://github.com/milenkovicm/wasaffi and @waynxia showed off a WASM playground: https://github.com/apache/arrow-datafusion/discussions/9834
* @peter-toth made `LogicalPlan` rewriting with `TreeNode` easier and faster: https://github.com/apache/arrow-datafusion/pull/9913
* @jayzhan211 began pulling aggregate functions out of the core: https://github.com/apache/arrow-datafusion/pull/9960
* "Extract scalar functions from the core" continues:  https://github.com/apache/arrow-datafusion/issues/9285 (thanks @erenavsarogullari and @Omega359 for keeping the 🚋  running here)
* Started talking about indexing: https://github.com/apache/arrow-datafusion/discussions/9963
* Started talking about ListingTable: https://github.com/apache/arrow-datafusion/issues/9964

## My (personal) goals 
1000 projects are built using DataFusion 📈 

## My (personal) plans for this week
- [x] https://github.com/sqlparser-rs/sqlparser-rs/issues/1162
- [ ] Reviews !
- [ ] Make query planning (at least) 2x faster https://github.com/apache/arrow-datafusion/issues/9637)
- [ ] Document `ParquetExec` more (so it is clear / easier to understand what is already supported and what else could be useful https://github.com/apache/arrow-datafusion/issues/9929)

## Project Queue (list of future projects)
- [ ] https://github.com/apache/arrow-datafusion/issues/9929

## Projects I plan to help actively help review / plan
- [ ] https://github.com/apache/arrow-rs/issues/5374
- [x] https://github.com/apache/arrow-datafusion/issues/9285
- [ ] https://github.com/apache/arrow-datafusion/issues/9494
- [ ] https://github.com/apache/arrow-datafusion/issues/9493 with @wiedld 

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://arrow.apache.org/committers/) who can and do review and merge PRs, so this is not the priorities of the project as a whole, just the approximate algorithm I use to prioritize my own time

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (my employer)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs that I think are strategically important
5. Other new features / additions to functionality (note this is the lowest)

The top strategically important projects in my head are:

* Anything that makes it easier to use DataFusion as a user (docs, examples, better APIs, etc), including [Getting started guide for new users (who want to use DataFusion in their project) ](https://github.com/apache/arrow-datafusion/issues/7014) 
* Anything that improves DataFusion's quality such as bug fixes, and improved / expanded tests, etc
* Making function packages modular and easier to mix/match: https://github.com/apache/arrow-datafusion/issues/8045 

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation or the projects named above

If you propose adding new functionality, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example, the CI passes, includes documentation, etc)

## Background
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week

**Comment by alamb** [comment]
@Omega359  get the 🍀  with lucky PR 10,000:  https://github.com/apache/arrow-datafusion/pull/10000

**Comment by Omega359** [comment]
It wasn't on purpose :)

**Comment by alamb** [comment]
Review Queue: 

DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/9983

**Comment by alamb** [comment]
BTW I don't think I say it enough, but @comphead  I really appreciate all the effort you put in to review PRs

**Comment by alamb** [comment]
Review Queue: 

DataFusion
- [x] https://github.com/apache/arrow-datafusion/pull/10008
- [ ] https://github.com/apache/arrow-datafusion/pull/9813
- [ ] https://github.com/apache/arrow-datafusion/pull/9991
- [ ] https://github.com/apache/arrow-datafusion/pull/9971
- [ ] https://github.com/apache/arrow-datafusion/pull/10006

sqlparser-rs:
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1181#
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1164

arrow-rs/parquet:
- [ ] https://github.com/apache/arrow-rs/pull/5557

**Comment by alamb** [comment]
Review Queue: 

DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/9813
- [ ] https://github.com/apache/arrow-datafusion/pull/9991
- [ ] https://github.com/apache/arrow-datafusion/pull/9971
- [ ] https://github.com/apache/arrow-datafusion/pull/10006

sqlparser-rs:
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1193
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1200

arrow-rs/parquet:
- [x] https://github.com/apache/arrow-rs/pull/5622#pullrequestreview-1991785578
- [ ] https://github.com/apache/arrow-rs/pull/5538

**Comment by alamb** [comment]
Review Queue: 

DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/10023
- [ ] https://github.com/apache/arrow-datafusion/pull/9971

arrow-rs/parquet:
- [ ] https://github.com/apache/arrow-rs/pull/5538
- [ ] https://github.com/apache/arrow-rs/pull/5557

sqlparser-rs:
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1181
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1193
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1200

**Comment by alamb** [comment]
Review Queue: 

DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/9971
- [ ] https://github.com/apache/arrow-datafusion/pull/10031

arrow-rs/parquet:
- [x] https://github.com/apache/arrow-rs/pull/5538
- [ ] https://github.com/apache/arrow-rs/pull/5557

sqlparser-rs:
- [x] https://github.com/sqlparser-rs/sqlparser-rs/pull/1212
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1181
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1193
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1200

**Comment by alamb** [comment]
4 BuiltInScalarFunctions left

**Comment by liukun4515** [comment]
> 4 BuiltInScalarFunctions left

Hi @alamb 
I scan some PRs about https://github.com/apache/arrow-datafusion/issues/9285, and find the the item of [datafusion/proto/proto/datafusion.proto](https://github.com/apache/arrow-datafusion/pull/9352/files#diff-dfbd8463b9c4a1e7ac21cf0154a33966bb72a86df15d5e1409906a08cbdeb4df) was deleted.

I have the question about this, how to serialize and deserialize the from other language to datafusion?

**Comment by alamb** [comment]
> I have the question about this, how to serialize and deserialize the other language logical plan/expr to datafusion?

I @liukun4515  -- the logical plan serialization / deserialization handles `ScalarUDF` and other user defined functions as before.

So for example, here is an example of how functions are serialized: 

https://github.com/apache/arrow-datafusion/blob/92318c808666695fb5c2f358083f1cb13158dca9/datafusion/proto/tests/cases/roundtrip_logical_plan.rs#L1867-L1892

**Comment by alamb** [comment]
Next week in https://github.com/apache/datafusion/issues/10172
