### ISSUE TITLE
[EPIC] A collection of improvements to optimize the speed of scalar functions

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#10171]
Here is a list of improvements to performance of scalar functions

- [x] https://github.com/apache/datafusion/issues/9742
- [x] https://github.com/apache/datafusion/issues/10007
- [x] https://github.com/apache/datafusion/issues/9970
- [x] https://github.com/apache/datafusion/issues/9890
- [x] https://github.com/apache/datafusion/issues/9089
- [x] https://github.com/apache/datafusion/issues/10228

**Comment by alamb** [comment]
Looks like all subtasks are done, so let's close this one
