### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - April 29, 2024

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#10283]
Follow on to https://github.com/apache/datafusion/issues/10172

**It would be great for other contributors to DataFusion who plan non trivial work could try to make them visible somehow as well** 🙏  (feel free to copy / modify the format)

## My Highlights from Last Week
* We have a new website https://datafusion.apache.org/ (with redirects from old urls) 🎉 
* We have worked through https://github.com/apache/arrow-datafusion/issues/9691 -- thanks to @phillipleblanc, @comphead, @andygrove and @tisonkun and @lewiszlw)
* We merged quite a few PRs for https://github.com/apache/datafusion/issues/9637 (e.g. [10184](https://github.com/apache/datafusion/pull/10184) and [10212](https://github.com/apache/datafusion/issues/10212). etc. Thanks to @peter-toth, @LordWorms, @kevinmingtarja)
* @jayzhan and @liukun cleaned up how zero argument handling works https://github.com/apache/datafusion/pull/10193
* @Jefffrey Added [`MEDIAN(DISTINCT ..)` support: ](https://github.com/apache/datafusion/pull/10226)The last aggregate without distinct support 
* @simonvandel made [date_bin (2x faster) (](https://github.com/apache/datafusion/commit/169701e0128911f16ed07e1ea714a4fdc1e90ee0)https://github.com/apache/datafusion/pull/10215[)](https://github.com/apache/datafusion/commit/169701e0128911f16ed07e1ea714a4fdc1e90ee0) 🚀 

## My (personal) goals 
1000 projects are built using DataFusion 📈 

## My (personal) plans for this week
- [ ] Support https://github.com/apache/arrow-datafusion/issues/9691 (complete https://github.com/apache/datafusion/issues/10135)
- [ ] Keep removing copies to make planning faster: https://github.com/apache/arrow-datafusion/issues/9637
- [ ] (Stretch goal) Document `ParquetExec` more (so it is clear / easier to understand what is already supported and what else could be useful https://github.com/apache/arrow-datafusion/issues/9929)

## Project Queue (list of future projects)
- [ ] https://github.com/apache/arrow-datafusion/issues/9929 (likely not this week)

## Projects I plan to help actively help review / plan
- [ ] https://github.com/apache/arrow-rs/issues/5374 (I am struggling to find time, but we are making progress, slowly)
- [ ] https://github.com/apache/datafusion/issues/10313
- [ ] https://github.com/apache/arrow-datafusion/issues/9494
- [ ] https://github.com/apache/arrow-datafusion/issues/9493 with @wiedld 

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://arrow.apache.org/committers/) who can and do review and merge PRs, so this is not the priorities of the project as a whole, just the approximate algorithm I use to prioritize my own time.

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (my employer)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs that I think are strategically important
5. Other new features / additions to functionality (note this is the lowest)

The top strategically important projects in my head are:

* Anything that makes it easier to use DataFusion as a user (docs, examples, better APIs, etc), including [Getting started guide for new users (who want to use DataFusion in their project) ](https://github.com/apache/arrow-datafusion/issues/7014) 
* Anything that improves DataFusion's quality such as bug fixes, and improved / expanded tests, etc
* Making function packages modular and easier to mix/match: https://github.com/apache/arrow-datafusion/issues/8045 

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation or the projects named above. 

If you propose adding new functionality, especially if the PR is large/complex and not connected to a wider need, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example, the CI passes, includes documentation, etc)

## Background
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week

**Comment by alamb** [comment]
Review Queue
- [ ] https://github.com/apache/datafusion/pull/10221
- [ ] https://github.com/apache/datafusion/pull/9593
- [ ] https://github.com/apache/datafusion/pull/10149
- [ ] https://github.com/apache/datafusion/pull/10208
- [ ] https://github.com/apache/datafusion/pull/10054

**Comment by alamb** [comment]
Inspired by https://github.com/apache/datafusion/pull/9593 from @suremarc , and https://github.com/apache/datafusion/issues/10257 from @nga, I started organizing sort based optimizations in a new epic: https://github.com/apache/datafusion/issues/10313

**Comment by alamb** [comment]
Review Queue
- [ ] https://github.com/apache/datafusion/pull/10268
- [ ] https://github.com/apache/datafusion/pull/10149
- [ ] https://github.com/apache/datafusion/pull/10208

Arrow
- [x] https://github.com/apache/arrow-rs/pull/5705#pullrequestreview-2036752575

**Comment by liukun** [comment]
> * @jayzhan and @liukun cleaned up how zero argument handling works [ScalarUDF: Remove `supports_zero_argument` and avoid creating null array for empty args #10193](https://github.com/apache/datafusion/pull/10193)
Should be @jayzhan211 and @liukun4515 .
Not me ;p

**Comment by alamb** [comment]
Sorry @liukun -- my bad

**Comment by alamb** [comment]
Next week: https://github.com/apache/datafusion/issues/10395
