### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - June 10, 2024

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#10869]
Follow on to https://github.com/apache/datafusion/issues/10779

My (personal) North ⭐ : 1000 projects are built using DataFusion 📈 

**It would be great for other contributors to DataFusion to to make them visible somehow as well** 🙏  (feel free to copy / modify the format of this ticket)

## External DataFusion 
* Released DataFusion 39.0.0: https://crates.io/crates/datafusion/39.0.0 
* ASF Press Release: https://news.apache.org/foundation/entry/apache-software-foundation-announces-new-top-level-project-apache-datafusion
* Cool example of building a parquet index using a remote catalog: https://github.com/datafusion-contrib/datafusion-async-parquet-index/pull/1 (kudos to @adriangb), 

## Feature Highlights
- New `AggregateBuilder` API: https://github.com/apache/datafusion/pull/10560 (thanks @jayzhan211)
- Support for parquet index https://github.com/apache/datafusion/issues/9929
- SIGMOD paper published officially ([ACM page](https://dl.acm.org/doi/10.1145/3626246.3653368)), talk this week: https://github.com/apache/datafusion/issues/10480
- Updated to arrow 52: https://github.com/apache/datafusion/pull/10765 (thanks @waynexia)
- Parquet statistics extraction more efficient https://github.com/apache/datafusion/pull/10711 (thanks @xinlifoobar)
- Updated to latest sqlparser: https://github.com/apache/datafusion/pull/10392 (thanks @tisonkun  and @jmhain)
- @jayzhan211, @goldmedal, @Lordworms,  @mknaw and others have been making great progress extracting aggregate functions from the core: https://github.com/apache/datafusion/issues/8708 🙏 ❤ 
- More efficient row group pruning in parquet exec:  https://github.com/apache/datafusion/pull/10802

## My (personal) plans for this week
- [x] SIGMOD and SiMOD talks https://github.com/apache/datafusion/issues/10480 / https://github.com/apache/datafusion/issues/10481
- [x] Complete example of parquet indexes: https://github.com/apache/datafusion/issues/10580
- [ ] Check out @Max-Meldrum's example index from https://github.com/apache/datafusion/discussions/9963#discussioncomment-9689550 
- [x] Help @XiangpengHao with https://github.com/apache/arrow-rs/issues/5374
- [x] Figure out why https://github.com/apache/datafusion/pull/10835 doesn't improve performance

## Project Queue (list of future projects)
- [ ] In general, help https://github.com/apache/arrow-rs/issues/5374 more actively as it seems to be stuck

## Projects I plan to help actively help review / plan
- [ ] https://github.com/apache/datafusion/issues/10806 (thanks to @marvinlanhenke for helping with DataPage)

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://projects.apache.org/committee.html?datafusion) who can and do review and merge PRs, so this is not the priorities of the project as a whole, just the approximate algorithm I use to prioritize my own time.

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (my employer)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs that I think are strategically important
5. Other new features / additions to functionality (note this is the lowest)

The top strategically important projects in my head are:

* Anything that makes it easier to use DataFusion as a user (docs, examples, better APIs, etc), including [Getting started guide for new users (who want to use DataFusion in their project) ](https://github.com/apache/arrow-datafusion/issues/7014) 
* Anything that improves DataFusion's quality such as bug fixes, and improved / expanded tests, etc
* Making function packages modular and easier to mix/match 
* Improved performance (with benchmarks)

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation or the projects named above. 

If you propose adding new functionality, especially if the PR is large/complex and not connected to a wider need, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example, the CI passes, includes documentation, etc)

## Background
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week

**Comment by alamb** [comment]
Follow on https://github.com/apache/datafusion/issues/10955
