### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - June 17, 2024

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#10955]
Follow on to https://github.com/apache/datafusion/issues/10869

My (personal) North ⭐ : 1000 projects are built using DataFusion 📈 

**It would be great for other contributors to DataFusion to to make them visible somehow as well** 🙏  (feel free to copy / modify the format of this ticket)

## Externally Facing Nes
* https://github.com/apache/datafusion/issues/10481 Keynote went well
* SIGMOD paper published officially ([ACM page](https://dl.acm.org/doi/10.1145/3626246.3653368)), talk went well: https://github.com/apache/datafusion/issues/10480
* @lewiszlw became a committer and @waynexia and @ozankabak joined the PMC 🎉 
* Meetup next week in SF organized by @cpard and @emgeee: https://github.com/apache/datafusion/discussions/10340
* Meetup in China being organized in July by @waynexia and @tisonkun : https://github.com/apache/datafusion/discussions/10341#discussioncomment-9738748

## Feature Highlights
* We are in the final phases of [converting all aggregate functions](https://github.com/apache/datafusion/issues/8708) thanks to @goldmedal with [this](https://github.com/apache/datafusion/pull/10917) , @dharanad with [this](https://github.com/apache/datafusion/pull/10930) @ejbyfeldt with [this](https://github.com/apache/datafusion/pull/10898) and @Lordworms with [this](https://github.com/apache/datafusion/pull/10851)
* Final example for building an external index is looking very nice https://github.com/apache/datafusion/issues/10580
* Substrait is becoming much better supported thanks to @Blizzara in [this](https://github.com/apache/datafusion/pull/10829) , [this](https://github.com/apache/datafusion/pull/10829) and others, and @Lordwords implementing [tests](https://github.com/apache/datafusion/pull/10842)
* We updated to 52.0.0 thanks to @waynexia https://github.com/apache/datafusion/pull/10765 🎉 

## My (personal) plans for this week
- [ ] Check out @Max-Meldrum's example index from https://github.com/apache/datafusion/discussions/9963#discussioncomment-9689550 
- [ ] Help @jayzhan211 with https://github.com/apache/datafusion/issues/9403
- [x] Work on some [better examples](https://github.com/apache/datafusion/issues/10855) of sql analysis with @LorrensP-2158466 and @goldmedal such as  https://github.com/apache/datafusion/pull/10938

## Projects I plan to help actively help review / plan
- [ ] https://github.com/apache/arrow-rs/issues/5374 with @XiangpengHao and others
- [ ] https://github.com/apache/datafusion/issues/10922 (with @marvinlanhenke @Weijun-H and others)

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://projects.apache.org/committee.html?datafusion) who can and do review and merge PRs, so this is not the priorities of the project as a whole, just the approximate algorithm I use to prioritize my own time.

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (my employer)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs that I think are strategically important
5. Other new features / additions to functionality (note this is the lowest)

The top strategically important projects in my head are:

* Anything that makes it easier to use DataFusion as a user (docs, examples, better APIs, etc), including [Getting started guide for new users (who want to use DataFusion in their project) ](https://github.com/apache/arrow-datafusion/issues/7014) 
* Anything that improves DataFusion's quality such as bug fixes, and improved / expanded tests, etc
* Making function packages modular and easier to mix/match 
* Improved performance (with benchmarks)

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation or the projects named above. 

If you propose adding new functionality, especially if the PR is large/complex and not connected to a wider need, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example, the CI passes, includes documentation, etc)

## Background
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week

**Comment by alamb** [comment]
Review Queue:
- [ ] https://github.com/apache/datafusion/pull/10473
- [ ] https://github.com/apache/datafusion/pull/11049
- [ ] https://github.com/apache/datafusion/pull/11035
- [ ] https://github.com/apache/datafusion/pull/11060
- [ ] https://github.com/apache/datafusion/pull/10792

**Comment by alamb** [comment]
Next week: https://github.com/apache/datafusion/issues/11106
