### ISSUE TITLE
Tracking issue: Overflow bugs in scalar math functions found by SQLancer

### ISSUE THREAD

**Issue by LorrensP-2158466** [apache/datafusion#11078]
SQLancer #11030 has found several overflow bugs in the math functions, this issue tracks those:
- [x] overflow in GCD & LCM #11053
- [x] Overflow bug in negate arithmetic operator #11076 (not sure if this should be also here)
- [x] Overflow bug in FACTORIAL scalar function  #11074 
- [x] Overflow bug in POW scalar function  #11075 

One question: should we fix each bug in a separate PR or 1 PR?

**Comment by alamb** [comment]
Amazing

**Comment by LorrensP-2158466** [comment]
I think all the overflows in these math functions are handled well, so I'm going to close this.

**Comment by alamb** [comment]
Thanks again @LorrensP-2158466  -- that made short work of them!
