### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - June 24, 2024

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11106]
Follow on to https://github.com/apache/datafusion/issues/10955

My (personal) North ⭐ : 1000 projects are built using DataFusion 📈 

**It would be great for other contributors to DataFusion to to make them visible somehow as well** 🙏  (feel free to copy / modify the format of this ticket)

## Externally Facing News
* Meetup  in SF organized by @cpard and @emgeee: https://github.com/apache/datafusion/discussions/10340
* Meetup in China being organized in July by @waynexia and @tisonkun : https://github.com/apache/datafusion/discussions/10341#discussioncomment-9738748

## Feature Highlights
* Support long requested API:  https://github.com/apache/datafusion/pull/10995 (thanks @xinlifoobar!)
* [Work to support StringView](https://github.com/apache/datafusion/issues/10918) has begun in earnest (thanks to @XiangpengHao, @PsiACE and @Weijun-H
* Converting SQL --> String is [getting](https://github.com/apache/datafusion/commit/41a788238cd60515de63598fb61ab842a74a9770) close to complete (thanks @goldmedal, 
* @2010YOUY01  [started testing DataFusion with `SQLancer`](https://github.com/apache/datafusion/issues/11030) and found  several bugs. Kudso to @LorrensP-2158466 for fixing a bunch of them already!
* @Omega359 added nice DataFrame APIs: [DataFrame::drop_column](https://github.com/apache/datafusion/pull/11010) and [DataFrame::distinct_on ](https://github.com/apache/datafusion/pull/11012)
* https://github.com/apache/datafusion/pull/10960 (Thanks @marvinlanhenke and @samuelcolvin!)
* [Parquet statistics are looking pretty](https://github.com/apache/datafusion/issues/10922) good thanks to @tshauck, @marvinlanhenke and @LorrensP-2158466 @tmi
* We are in the final phases of [converting all aggregate functions](https://github.com/apache/datafusion/issues/8708) -- thanks to [this](https://github.com/apache/datafusion/issues/10942) from @dharanad and others
* Merged https://github.com/apache/datafusion/issues/10580

## My (personal) plans for this week
- [x] Present at DataFusion Meetup in SF ([slides](https://docs.google.com/presentation/d/1Oz2yGllrWBkNGyiRMLr8qXTt4vmvtJWuI_weGThaZak/edit#slide=id.g26bebde4fcc_3_7))
- [x] https://github.com/apache/datafusion/issues/10969
- [ ] https://github.com/apache/datafusion/issues/10282
- [ ] https://github.com/apache/datafusion/issues/4028
- [ ] https://github.com/apache/datafusion/issues/9602
- [ ] Check out @Max-Meldrum's example index from https://github.com/apache/datafusion/discussions/9963#discussioncomment-9689550
- [ ] Help @jayzhan211 with faster multi-column aggregation https://github.com/apache/datafusion/issues/9403 (needs some optimizer work)

## Projects I plan to help actively help review / plan
- [ ] https://github.com/apache/arrow-rs/issues/5374 with @XiangpengHao and others
- [ ] https://github.com/apache/datafusion/issues/10922 (with @marvinlanhenke @Weijun-H and others)

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://projects.apache.org/committee.html?datafusion) who can and do review and merge PRs, so this is not the priorities of the project as a whole, just the approximate algorithm I use to prioritize my own time.

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (my employer)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs that I think are strategically important
5. Other new features / additions to functionality (note this is the lowest)

The top strategically important projects in my head are:

* Anything that makes it easier to use DataFusion as a user (docs, examples, better APIs, etc), including [Getting started guide for new users (who want to use DataFusion in their project) ](https://github.com/apache/arrow-datafusion/issues/7014) 
* Anything that improves DataFusion's quality such as bug fixes, and improved / expanded tests, etc
* Making function packages modular and easier to mix/match 
* Improved performance (with benchmarks)

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation or the projects named above. 

If you propose adding new functionality, especially if the PR is large/complex and not connected to a wider need, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example, the CI passes, includes documentation, etc)

## Background
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week

**Comment by alamb** [comment]
Review Queue:
- [ ] https://github.com/apache/datafusion/pull/11035
- [ ] https://github.com/apache/datafusion/pull/10792

Arrow
- [ ] https://github.com/apache/arrow-rs/pull/5939

**Comment by alamb** [comment]
Arrow
- [ ] https://github.com/apache/arrow-rs/pull/5486

**Comment by alamb** [comment]
Next week: https://github.com/apache/datafusion/issues/11190
