### ISSUE TITLE
[EPIC] Improve examples to make them easier to navigate

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11172]
### Is your feature request related to a problem or challenge?

The current number of examples in https://github.com/apache/datafusion/tree/main/datafusion-examples is somewhat overwhelming and hard to navigate

### Describe the solution you'd like

I would like fewer consolidated examples. For example a `sql.rs` example rather than SQL examples being spread out across (at least) 9 different files

* parqet_sql
* parqet_sql_multiple_files
* regexp
* to_char
* to_date
* to_timestamp
* make_date
* avro_sql.rs

# Subtasks
- [x] https://github.com/apache/datafusion/issues/13842
- [x] https://github.com/apache/datafusion/issues/13844
- [x] https://github.com/apache/datafusion/issues/13843
- [x] https://github.com/apache/datafusion/issues/11230
- [x] https://github.com/apache/datafusion/issues/11210
- [x] https://github.com/apache/datafusion/issues/1813
- [x] https://github.com/apache/datafusion/issues/13911
- [x] https://github.com/apache/datafusion/issues/13912
- [x] https://github.com/apache/datafusion/issues/13938
- [x] https://github.com/apache/datafusion/issues/13955
- [ ] https://github.com/apache/datafusion/pull/13954

### Additional context

Also, I am trying to add some new examples, but the CI in my PR https://github.com/apache/datafusion/pull/11088 is failing due to running out of space

Example failure: https://github.com/apache/datafusion/actions/runs/9715084012/job/26815819949

```
  = note: /usr/bin/ld: final link failed: No space left on device
          collect2: error: ld returned 1 exit status
```

I think it is because each example creates its own binary which fills up the disk

Thus I also want to reduce the number of examples so I can add new ones :)

**Comment by alamb** [comment]
While working with @lewiszlw in https://github.com/apache/datafusion/pull/11173#issuecomment-2198280594 I think I came up with a better idea -- that is to update the user guide so they code examples are run / tested

Then we can move many/all of the examples from rust to the user guide, which will make them easier to find and navigate. 🏃

**Comment by alamb** [comment]
I played around with what we have and it turns out I think we can test examples in the user guide. I made a PR with docs of how to do it: https://github.com/apache/datafusion/pull/11178

I think with that framework we could add many of the simpler examples directly into the documentation where they would be eaiser to find. We can leave the more complex ones in datafusion-examples perhaps

Thoughts?

**Comment by efredine** [comment]
As a newcomer I'll say that this seems right to me. Examples that are right in the documentation are much more discoverable.

**Comment by alamb** [comment]
I plan do to this as a background task, but realistically can't devote enough focus time to it now

**Comment by logan-keede** [comment]
take

**Comment by alamb** [comment]
Thank you @logan-keede 🙏 

After https://github.com/apache/datafusion/pull/14240 I don't think there is any example left for consolidation that I can see

**Comment by logan-keede** [comment]
@alamb I think there is one more thing we can do, though perhaps it is only my preference.

We can consolidate them into folders, a big `sql.rs` might hinder ease of navigation, but if we are going to keep adding examples it might be better to have them in a directory, we can do that for other general domains like `parquet` and `csv` too.

Except that, I think we can close this issue.

**Comment by alamb** [comment]
> [@alamb](https://github.com/alamb) I think there is one more thing we can do, though perhaps it is only my preference.
> 
> We can consolidate them into folders, a big `sql.rs` might hinder ease of navigation, but if we are going to keep adding examples it might be better to have them in a directory, we can do that for other general domains like `parquet` and `csv` too.
> 
> Except that, I think we can close this issue.

I actually think keping them in a single directory, while somewhat overwhelming, is good for discoverability (aka knowing what is available) so until we get more I would recommend we keep it that way
