### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - July 1, 2024

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11190]
Follow on to https://github.com/apache/datafusion/issues/11106

My (personal) North ⭐ : 1000 projects are built using DataFusion 📈 

**It would be great for other contributors to DataFusion to to make them visible somehow as well** 🙏  (feel free to copy / modify the format of this ticket)

## Externally Facing News
* Meetup  in SF went great thanks to @cpard and @emgeee https://github.com/apache/datafusion/discussions/10800
* Talk at MSR went well: https://github.com/apache/datafusion/issues/10969

## Feature Highlights
* https://github.com/apache/datafusion/pull/11107 with @hveiga
* https://github.com/apache/datafusion/pull/11060 from @devinjdangelo (and fast follow on https://github.com/apache/datafusion/pull/11174 docs from @tshauck)
* @Blizzara continues to churn through making substrait better: https://github.com/apache/datafusion/pull/11129
* @2010YOUY01  found a bunch of corner cases in SQLancer https://github.com/apache/datafusion/issues/11030 and then @LorrensP-2158466, @jonahgao and others fixed corner cases like https://github.com/apache/datafusion/issues/11075

## My (personal) plans for this week
- [ ] https://github.com/apache/datafusion/issues/10282
- [ ] https://github.com/apache/datafusion/issues/9602
- [ ] SQLParser release: https://github.com/sqlparser-rs/sqlparser-rs/issues/1296
- [x] https://github.com/apache/arrow-rs/issues/5905
- [ ] Faster multi-column aggregation with @jayzhan211  https://github.com/apache/datafusion/issues/9403 (https://github.com/apache/datafusion/pull/11177 was a step towards this)

## Project Queue (list of future projects)
- [ ] https://github.com/apache/datafusion/issues/4028

## Projects I plan to help actively help review / plan
- [ ] Help user defined SQL planner API https://github.com/apache/datafusion/issues/10534 with @jayzhan211 and @samuelcolvin, e.g. https://github.com/apache/datafusion/pull/11180)
- [ ] Help push USAD over the line (https://github.com/apache/datafusion/issues/8708 -- e.g. https://github.com/apache/datafusion/issues/10943 . Thanks to @edmondop)
- [ ] https://github.com/apache/datafusion/issues/10922 (I hope to finish the last few items, with @efredine,  @dharanad and others)
- [ ] https://github.com/apache/arrow-rs/issues/5374 and https://github.com/apache/datafusion/issues/10918 with @XiangpengHao and others

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://projects.apache.org/committee.html?datafusion) who can and do review and merge PRs, so this is not the priorities of the project as a whole, just the approximate algorithm I use to prioritize my own time.

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (my employer)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs that I think are strategically important
5. Other new features / additions to functionality (note this is the lowest)

The top strategically important projects in my head are:

* Anything that makes it easier to use DataFusion as a user (docs, examples, better APIs, etc), including [Getting started guide for new users (who want to use DataFusion in their project) ](https://github.com/apache/arrow-datafusion/issues/7014) 
* Anything that improves DataFusion's quality such as bug fixes, and improved / expanded tests, etc
* Making function packages modular and easier to mix/match 
* Improved performance (with benchmarks)

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation or the projects named above. 

If you propose adding new functionality, especially if the PR is large/complex and not connected to a wider need, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example, the CI passes, includes documentation, etc)

## Background
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week

**Comment by alamb** [comment]
Review Queue

DataFusion
- [ ] https://github.com/apache/datafusion/pull/11160

Arrow
- [ ] https://github.com/apache/arrow-rs/pull/5486

**Comment by alamb** [comment]
Review Queue

DataFusion
- [ ] https://github.com/apache/datafusion/pull/11186
- [ ] https://github.com/apache/datafusion/pull/11197
- [ ] https://github.com/apache/datafusion/pull/11196

**Comment by alamb** [comment]
Review Queue

DataFusion
- [ ] https://github.com/apache/datafusion/pull/11035
- [ ] https://github.com/apache/datafusion/pull/10792

**Comment by samuelcolvin** [comment]
I'd love to get https://github.com/apache/arrow-rs/pull/5994 merged and released fairly soon if at all possible 🤞 🙏 .

**Comment by alamb** [comment]
Review Queue

Arrow
- [ ] https://github.com/apache/arrow-rs/pull/5486

DataFusion
- [ ] https://github.com/apache/datafusion/pull/11035
- [ ] https://github.com/apache/datafusion/pull/10792

**Comment by alamb** [comment]
Next week in https://github.com/apache/datafusion/issues/11334
