### ISSUE TITLE
[Epic] Complete pulling out special SQL planning from the Sql Parser

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11207]
### Is your feature request related to a problem or challenge?

As discussed in https://github.com/apache/datafusion/issues/10534, @jayzhan211  added a `UserDefinedSQLPlanner` in https://github.com/apache/datafusion/pull/11180 so that the translation of certain SQL sytanx to `LogicalPlan`s and `Expr`s are not hard coded in `SqlToRel` but instead are controlled by a `UserDefinedSQLPlanner`

Now that we have the pattern, we need to move the other remaining functionality that is hard coded (e.g. looking up a function "date_part" by name) in SqlToRel to the UserDefinedSQLPlanner

### Describe the solution you'd like

To rewrite with sql planner
- [x] https://github.com/apache/datafusion/pull/11215
- [x] https://github.com/apache/datafusion/issues/11220
- [x] https://github.com/apache/datafusion/issues/11221
- [x] https://github.com/apache/datafusion/issues/11222
- [x] https://github.com/apache/datafusion/issues/11223
- [x] https://github.com/apache/datafusion/issues/11304
- [x] sql_position_to_expr
- [x] sql_substring_to_expr
- [x] #11473
- [x] https://github.com/apache/datafusion/issues/11216
- [x] https://github.com/apache/datafusion/issues/11294
- [x] https://github.com/apache/datafusion/issues/11305
- [x] https://github.com/apache/datafusion/pull/11341

### Additional context

Discussion is here: https://github.com/apache/datafusion/issues/10534

**Comment by samuelcolvin** [comment]
#11208 allows user defined sql planners to be defined.

**Comment by dharanad** [comment]
hello @alamb Just checking in on the remaining tasks. Is there anything specific we're waiting on before we create issues ?
If we're all set, i would be happy to jump in and get started to pick up few tasks.

**Comment by alamb** [comment]
> hello @alamb Just checking in on the remaining tasks. Is there anything specific we're waiting on before we create issues ? If we're all set, i would be happy to jump in and get started to pick up few tasks.

Hi @dharanad  I don't think there is anything from my perspective. Thank you for offering

In fact it seems as if @xinlifoobar  has already started with https://github.com/apache/datafusion/pull/11215 ❤️

**Comment by dharanad** [comment]
I've created issues for a couple of tasks. Please let me know if you think anything needs updating in the descriptions. I'm new here and learning from the experienced folks like Shadowing

* date_part : https://github.com/apache/datafusion/issues/11220
* create_struct : https://github.com/apache/datafusion/issues/11221
* create_named_struct : https://github.com/apache/datafusion/issues/11222
* sql_overlay_to_expr : https://github.com/apache/datafusion/issues/11223

**Comment by alamb** [comment]
> I've created issues for a couple of tasks. Please let me know if you think anything needs updating in the descriptions. I'm new here and learning from shadowing the experienced folks

thank you @dharanad  -- this is very helpful 🙏

**Comment by alamb** [comment]
FWIW in general @dharanad  I have had the best luck with writing a description on tickets that requires as little context as possible (aka distill down what is needed into the the description, rather than assuming the new contributor will read the epic and get all the backstory)

The rationale for this duplication is to lower the barrier to new contrbutors

**Comment by dharanad** [comment]
> FWIW in general @dharanad  I have had the best luck with writing a description on tickets that requires as little context as possible (aka distill down what is needed into the the description, rather than assuming the new contributor will read the epic and get all the backstory)
> 
> 
> 
> The rationale for this duplication is to lower the barrier to new contrbutors

Thanks for the feedback! I really appreciate. You're right, making the ticket description concise and self-contained will definitely help reduce the barrier for new contributors. I'll update the description to include the necessary context. Thanks you

**Comment by dharanad** [comment]
Create issues for the remaining tasks, tried adding a description based on my understanding of the issue. Also update the same for the older ones

* `sql_compound_identifier_to_expr`: https://github.com/apache/datafusion/issues/11244
* `sql_substring_to_expr` : https://github.com/apache/datafusion/issues/11245
* `sql_position_to_expr`: https://github.com/apache/datafusion/issues/11246

**Comment by samuelcolvin** [comment]
Given how much `UserDefinedSQLPlanner` is being used for existing stuff within datafusion, perhaps it should be called just `SQLPlanner` or `CustomSQLPlanner`?

**Comment by alamb** [comment]
> Given how much `UserDefinedSQLPlanner` is being used for existing stuff within datafusion, perhaps it should be called just `SQLPlanner` or `CustomSQLPlanner`?

I agree

Or maybe something like `ExprPlanner` 🤔  as it is being used to plan specific exprs.

**Comment by samuelcolvin** [comment]
`ExprPlanner` sounds good.

**Comment by xinlifoobar** [comment]
Given #11220 and #11243, those are very similar APIs with UDF plans. I am trying to draft an API, e.g.,

```
    // Plan the user defined function, returns origin expression arguments if not possible
    fn plan_udf(
        &self,
        _sql: &sqlparser::ast::Expr,
        args: Vec<Expr>,
    ) -> Result<PlannerResult<Vec<Expr>>> {
        Ok(PlannerResult::Original(args))
    }
```

to uniform the usages. 

I have created a draft PR #11263 to discuss this. The flaw here is that the parameter `sql` is partially borrowed and has to be cloned at the very beginning. Maybe we should consider use reference instead.

**Comment by xinlifoobar** [comment]
> Given #11220 and #11243, those are very similar APIs with UDF plans. I am trying to draft an API, e.g.,
> 
> ```
>     // Plan the user defined function, returns origin expression arguments if not possible
>     fn plan_udf(
>         &self,
>         _sql: &sqlparser::ast::Expr,
>         args: Vec<Expr>,
>     ) -> Result<PlannerResult<Vec<Expr>>> {
>         Ok(PlannerResult::Original(args))
>     }
> ```
> 
> to uniform the usages.
> 
> I have created a draft PR #11263 to discuss this. The flaw here is that the parameter `sql` is partially borrowed and has to be cloned at the very beginning. Maybe we should consider using references if possible.

Eventually, I made this #11263, please let me know your thoughts. Thanks :)

CC @jayzhan211 @dharanad @alamb

**Comment by alamb** [comment]
> `ExprPlanner` sounds good.

Filed https://github.com/apache/datafusion/issues/11304

**Comment by alamb** [comment]
I think we are pretty close to calling this done. 

I just double checked and `sql_compound_identifier_to_expr` is the only thing that needs this treatment to remove the call to `get_function_meta`: 

https://github.com/apache/datafusion/blob/bfd815622f1fe2c84d6fab32596b83ffbe52a84a/datafusion/sql/src/expr/identifier.rs#L138-L139

That appears to be the last issue
https://github.com/search?q=repo%3Aapache%2Fdatafusion+get_function_meta+path%3A%2F%5Edatafusion%5C%2Fsql%5C%2F%2F&type=code

**Comment by alamb** [comment]
Filed https://github.com/apache/datafusion/issues/11473

**Comment by alamb** [comment]
I think we can claim we are done 🎉 

thanks everyone
