### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - July 8, 2024

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11334]
Follow on to https://github.com/apache/datafusion/issues/11190

My (personal) North ⭐ : 1000 projects are built using DataFusion 📈 

**It would be great for other contributors to DataFusion to to make them visible somehow as well** 🙏  (feel free to copy / modify the format of this ticket)

## Externally Facing News
DataFusion mentioned in ["What goes around, comes around... and around...."](https://t.co/ZwTWSxXLWb) paper from Andy Pavlo and Mike Stonebreaker
https://twitter.com/andy_pavlo/status/1807799839616614856

## Feature Highlights
* [Introduce user defined SQL planner API](https://github.com/apache/datafusion/pull/11180#top) from @jayzhan211
* [docs: add example for custom file format with COPY TO](https://github.com/apache/datafusion/pull/11174#top) @tshauk
* @lewiszlw continues to make the code better  https://github.com/apache/datafusion/pull/11239  ❤ 
* @Blizzara and @LordWorms continue to bash out substrait support (they are up to tpch q4 and 5)! https://github.com/apache/datafusion/pull/11298
* @jayzhan211 supported DUCKDB style struct syntax: https://github.com/apache/datafusion/pull/11214 

```sql
> select {'foo': 1};
+------------------------------------+
| named_struct(Utf8("foo"),Int64(1)) |
+------------------------------------+
| {foo: 1}                           |
+------------------------------------+
1 row(s) fetched.
Elapsed 0.015 seconds.

> select {'foo': {'bar': 2}};
+--------------------------------------------------------------+
| named_struct(Utf8("foo"),named_struct(Utf8("bar"),Int64(2))) |
+--------------------------------------------------------------+
| {foo: {bar: 2}}                                              |
+--------------------------------------------------------------+
1 row(s) fetched.
Elapsed 0.002 seconds.
```

## My (personal) plans for this week
- [x] SQLParser release: https://github.com/sqlparser-rs/sqlparser-rs/issues/1296
- [ ] "move the needle" projects:  improve docs  + writing https://github.com/apache/datafusion/issues/11172 https://github.com/apache/datafusion/issues/9602, 
- [ ] (Fun Project): Faster multi-column aggregation with @jayzhan211  https://github.com/apache/datafusion/issues/9403 (https://github.com/apache/datafusion/pull/11177 was a step towards this)
- [x] https://github.com/apache/datafusion/issues/10282

## Projects I plan to help actively help review / plan
- [ ] Complete  SQL planner extension API https://github.com/apache/datafusion/issues/10534 with @jayzhan211 and @samuelcolvin, @xinlifoobar, @dharanad)
- [ ] Various upstream parquet metadata changes:  https://github.com/apache/arrow-rs/pull/6000, https://github.com/apache/arrow-rs/pull/6011, https://github.com/apache/arrow-rs/pull/5486, 
- [ ] Help push user defined aggregates over the line (https://github.com/apache/datafusion/issues/8708) - thanks to @Rachelint and @jcsherin)

- [ ] https://github.com/apache/datafusion/issues/10922 (kudos to @Rachelint and @efredine) most of what is left is porting it upstream to arrow-rs)
- [ ] https://github.com/apache/arrow-rs/issues/5374 and https://github.com/apache/datafusion/issues/10918 with @XiangpengHao and others

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://projects.apache.org/committee.html?datafusion) who can and do review and merge PRs, so this is not the priorities of the project as a whole, just the approximate algorithm I use to prioritize my own time.

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (my employer)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs that I think are strategically important
5. Other new features / additions to functionality (note this is the lowest)

The top strategically important projects in my head are:

* Anything that makes it easier to use DataFusion as a user (docs, examples, better APIs, etc), including [Getting started guide for new users (who want to use DataFusion in their project) ](https://github.com/apache/arrow-datafusion/issues/7014) 
* Anything that improves DataFusion's quality such as bug fixes, and improved / expanded tests, etc
* Making function packages modular and easier to mix/match 
* Improved performance (with benchmarks)

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation or the projects named above. 

If you propose adding new functionality, especially if the PR is large/complex and not connected to a wider need, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example, the CI passes, includes documentation, etc)

## Background
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week

**Comment by alamb** [comment]
Review Queue

Arrow
- [ ] https://github.com/apache/arrow-rs/pull/6000
- [ ] https://github.com/apache/arrow-rs/pull/6011
- [ ] https://github.com/apache/arrow-rs/pull/5486
- [ ] https://github.com/apache/arrow-rs/pull/6006

DataFusion
- [ ] https://github.com/apache/datafusion/pull/11035
- [ ] https://github.com/apache/datafusion/pull/11289
- [ ] https://github.com/apache/datafusion/pull/10792

**Comment by alamb** [comment]
I am so behind on reviews. I hope to try and catch up tomorrow

**Comment by alamb** [comment]
Review Queue

Arrow
- [ ] https://github.com/apache/arrow-rs/pull/6046
- [ ] https://github.com/apache/arrow-rs/pull/6045
- [ ] https://github.com/apache/arrow-rs/pull/6044
- [ ] https://github.com/apache/arrow-rs/pull/6043
- [ ] https://github.com/apache/arrow-rs/pull/6025
- [ ] https://github.com/apache/arrow-rs/pull/6021

DataFusion
- [ ] https://github.com/apache/datafusion/pull/11289
- [ ] https://github.com/apache/datafusion/pull/11371
- [ ] https://github.com/apache/datafusion/pull/11035
- [ ] https://github.com/apache/datafusion/pull/10792
- [ ] https://github.com/apache/datafusion/pull/11218

**Comment by alamb** [comment]
Review Queue

Arrow
- [ ] https://github.com/apache/arrow-rs/pull/6046
- [ ] https://github.com/apache/arrow-rs/pull/6021


DataFusion: 
- [ ] https://github.com/apache/datafusion/pull/11456
- [ ] https://github.com/apache/datafusion/pull/11421
- [ ] https://github.com/apache/datafusion/pull/11289
- [ ] https://github.com/apache/datafusion/pull/11035
- [ ] https://github.com/apache/datafusion/pull/10792

**Comment by alamb** [comment]
Next week https://github.com/apache/datafusion/issues/11474
