### ISSUE TITLE
[EPIC] A collection of issues for supporting the `MAP` DataType

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11429]
### Describe the solution you'd like

- [ ] https://github.com/apache/datafusion/issues/11128
- [ ] https://github.com/apache/datafusion/issues/8262
- [ ] https://github.com/apache/datafusion/issues/11268

**Comment by goldmedal** [comment]
I have created the follow-up issues for https://github.com/apache/datafusion/issues/11268:
- [ ] https://github.com/apache/datafusion/issues/11434
- [ ] https://github.com/apache/datafusion/issues/11435
- [ ] https://github.com/apache/datafusion/issues/11436
- [ ] https://github.com/apache/datafusion/issues/11437

**Comment by alamb** [comment]
> I have created the follow-up issues for #11268:

Awesome -- thank you @goldmedal  -- I added them to the ticket description too

**Comment by goldmedal** [comment]
I guess it's also related to this epic
- [ ] https://github.com/apache/datafusion/issues/11546

**Comment by Weijun-H** [comment]
related
- #12147
- #12148

**Comment by alamb** [comment]
It looks to me like we have completed most of the planned work here and it is no longer active so closing it down to clean up our tickets a bit. Thanks again everyone
