### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - July 15, 2024

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11474]
My (personal) North ⭐ : 1000 projects are built using DataFusion 📈 

**It would be great for other contributors to DataFusion to to make them visible somehow as well** 🙏  (feel free to copy / modify the format of this ticket)

## Externally Facing News
* https://github.com/apache/datafusion/discussions/11431
* https://github.com/apache/datafusion/discussions/11213
* See discussion of roadmap: https://github.com/apache/datafusion/issues/11442
* Expr --> SQL is now optionally much prettier: https://github.com/apache/datafusion/pull/11186 thanks to @MohamedAbdeen21
* @dharanad moved https://github.com/apache/datafusion/issues/11207 close to complete ❤ 

## Feature Highlights
*  between @Lordworms and @Blizzara substrait support is quite complete now (see  https://github.com/apache/datafusion/pull/11462)
* CSE is getting even better thanks to @peter-toth: https://github.com/apache/datafusion/pull/11357
* DataFusion can make `MAP` scalars now: https://github.com/apache/datafusion/pull/11361 thanks to @goldmedal

## My (personal) plans for this week
- [ ] https://github.com/apache/datafusion/issues/11172 https://github.com/apache/datafusion/issues/9602, 
- [ ] (Fun Project): Faster multi-column aggregation 

## Projects I plan to help actively help review / push forward
- [ ] Help complete https://github.com/apache/datafusion/issues/10922 @efredine has https://github.com/apache/arrow-rs/pull/6046
- [ ] Complete  SQL planner extension API https://github.com/apache/datafusion/issues/10534 with @jayzhan211 and @samuelcolvin, @xinlifoobar, @dharanad)
- [ ] Various upstream parquet metadata changes:  https://github.com/apache/arrow-rs/pull/6000, https://github.com/apache/arrow-rs/pull/6011, https://github.com/apache/arrow-rs/pull/5486, 
- [ ] Help push user defined aggregates over the line (https://github.com/apache/datafusion/issues/8708) - thanks to @Rachelint and @jcsherin)
- [ ] https://github.com/apache/arrow-rs/issues/5374 and https://github.com/apache/datafusion/issues/10918 with @XiangpengHao and others

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://projects.apache.org/committee.html?datafusion) who can and do review and merge PRs, so this is not the priorities of the project as a whole, just the approximate algorithm I use to prioritize my own time.

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (my employer)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs for other features I think are strategically important (See below)
5. Other new features / additions to functionality (note this is the lowest on purpose)

The top strategically important projects in my head are:

* Anything that makes it easier to use DataFusion as a user (docs, examples, better APIs, etc), including [Getting started guide for new users (who want to use DataFusion in their project) ](https://github.com/apache/arrow-datafusion/issues/7014) 
* Anything that improves DataFusion's quality such as bug fixes, and improved / expanded tests, etc
* Improved performance (with benchmarks)

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation or the projects named above. 

If you propose adding new functionality, especially if the PR is large/complex and not connected to a wider need, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example, the CI passes, includes documentation, etc)

## Background
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week

**Comment by alamb** [comment]
Review Queue

Arrow
- [x] https://github.com/apache/arrow-rs/pull/6053
- [ ] https://github.com/apache/arrow-rs/pull/6046
- [ ] https://github.com/apache/arrow-rs/pull/6021


DataFusion: 
- [ ] https://github.com/apache/datafusion/pull/11453
- [ ] https://github.com/apache/datafusion/pull/11456
- [ ] https://github.com/apache/datafusion/pull/11421
- [ ] https://github.com/apache/datafusion/pull/11289
- [ ] https://github.com/apache/datafusion/pull/11035
- [ ] https://github.com/apache/datafusion/pull/10792

**Comment by alamb** [comment]
Arrow:
- [ ] https://github.com/apache/arrow-rs/issues/6097
- [ ] https://github.com/apache/arrow-rs/pull/6021

**Comment by alamb** [comment]
Next week: https://github.com/apache/datafusion/issues/11601
