### ISSUE TITLE
[EPIC] Extract remaining physical optimizer out of core

### ISSUE THREAD

**Issue by jayzhan211** [apache/datafusion#11502]
### Is your feature request related to a problem or challenge?

Historically DataFusion was one (very) large crate `datafusion`, and as it grew bigger we extracted various functionality into separate crates. This leads to both faster compile times (as the crates can be compiled in parallel) as well easier to navigate code (as the crates force a cleaner dependency separation)

This project tracks moving the physical optimizers:

* The original physical optimizers are here https://github.com/apache/datafusion/tree/main/datafusion/core/src/physical_optimizer
* The new crate is here  https://github.com/apache/datafusion/tree/main/datafusion/physical-optimizer

### Describe the solution you'd like

Pull physical optimizer rules to `datafusion-physical-optimizer`.

There are some tests that have dependencies on `datasource`, which they are not possible to move out of core at this moment. We may need to leave those tests inside core for now.

- [x] PhysicalOptimizerRule #11507
- [x] OutputRequirements
- [x] AggregateStatistics
- [x] https://github.com/apache/datafusion/issues/14073
- [x] LimitedDistinctAggregation
- [ ] EnforceDistribution
- [x] CombinePartialFinalAggregate
- [ ] EnforceSorting
- [ ] OptimizeAggregateOrder
- [ ] ProjectionPushdown
- [ ] CoalesceBatches
- [ ] OutputRequirements
- [x] TopKAggregation
- [x] https://github.com/apache/datafusion/issues/14072
- [ ] https://github.com/apache/datafusion/issues/14184
- [x] #14185
- [x] #14186
- [ ] Move `PhysicalOptimizer` and any remaining crates into `datafusion-physical-optimizer` crate, remove datafusion/core/physical-optimizer

**Comment by jonathanc-n** [comment]
@jayzhan211 @lewiszlw How do we plan on moving the rest of the functions. If we move the tests separately many of the tests depend on the traits in the functions that are being moved. Due to this it would make sense to import together, but then problems with the datasource and other util dependencies will pop up again. Do you guys have any solutions in mind?

**Comment by jayzhan211** [comment]
We may need to move `datasource` out of core

**Comment by jayzhan211** [comment]
Try to move optimization that doesn't have datasource dependency like 

- [ ] replace_with_order_preserving_variants
- [ ] sanity_checker
- [ ] sort_pushdown
- [ ] enforce_distribution
- [ ] join_selection

If we only need datasource in test, leave the test in core

**Comment by jonathanc-n** [comment]
@jayzhan211 Would you like to open a ticket for moving datasource out of core, so others are more aware of this transition?

**Comment by jayzhan211** [comment]
> @jayzhan211 Would you like to open a ticket for moving datasource out of core, so others are more aware of this transition?

Not sure how do achieve this yet, the high level idea is tracked in #10782

**Comment by josh0yeh** [comment]
take

**Comment by alamb** [comment]
I filed some small tickets to get this project moving again:
- https://github.com/apache/datafusion/issues/14072
-  https://github.com/apache/datafusion/issues/14073

**Comment by alamb** [comment]
I filed a last few tickets
- https://github.com/apache/datafusion/issues/14184
- https://github.com/apache/datafusion/issues/14185
- https://github.com/apache/datafusion/issues/14186

Once those are moved I think we can move the last remnants of the physical optimizer and close this ticket

**Comment by alamb** [comment]
We did it! Thank you @buraksenn @berkaysynnada and @logan-keede  for pushing it the last little bit
