### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - July 22, 2024

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11601]
Follow on to https://github.com/apache/datafusion/issues/11474

My (personal) North ⭐ : 1000 projects are built using DataFusion 📈 

**It would be great for other contributors to DataFusion to to make them visible somehow as well** 🙏  (feel free to copy / modify the format of this ticket)

# Major Discussions (I would encourage to take a look)
* roadmap: https://github.com/apache/datafusion/issues/11442
* Logical Types: https://github.com/apache/datafusion/issues/11513 from @notfilippo 
* Split out catalog (and change `TableProvider`): https://github.com/apache/datafusion/pull/11516 from @findepi
* https://github.com/apache/arrow-rs/pull/6000: Apis for working with parquet metadata from @adriangb

## External news
* Meetup in Hangzhou,  China 🎉  https://github.com/apache/datafusion/discussions/10341#discussioncomment-10110273 (thanks @waynexia , @tisonkun and @liukun4515 

## Upcoming Meetups
* https://github.com/apache/datafusion/discussions/11431
* https://github.com/apache/datafusion/discussions/11213

## Feature Highlights
*  Completed https://github.com/apache/datafusion/issues/10922 @efredine has https://github.com/apache/arrow-rs/pull/6046 🎉 
- Completed  SQL planner extension API https://github.com/apache/datafusion/issues/10534 with @jayzhan211 and @samuelcolvin, @xinlifoobar, @dharanad)

## My (personal) plans for this week
- [ ] Finish Blog: https://github.com/apache/datafusion/issues/9602, 
- [ ] Work down the review backlogs 

## Projects I plan to help actively help review / push forward
- [ ] Various upstream parquet metadata changes:  https://github.com/apache/arrow-rs/pull/6000, https://github.com/apache/arrow-rs/pull/6011, https://github.com/apache/arrow-rs/pull/5486, with @etseidl and @adriangb
- [ ] Help push user defined aggregates over the line (https://github.com/apache/datafusion/issues/8708) - thanks to @Rachelint and @jcsherin)
- [ ] https://github.com/apache/arrow-rs/issues/5374 and https://github.com/apache/datafusion/issues/10918 with @XiangpengHao @a10y and others

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://projects.apache.org/committee.html?datafusion) who can and do review and merge PRs, so this is not the priorities of the project as a whole, just the approximate algorithm I use to prioritize my own time.

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (my employer)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs for other features I think are strategically important (See below)
5. Other new features / additions to functionality (note this is the lowest on purpose)

The top strategically important projects in my head are:

* Improved performance (with benchmarks -- this is higher in my mind now)
* Anything that makes it easier to use DataFusion as a user (docs, examples, better APIs, etc), including [Getting started guide for new users (who want to use DataFusion in their project) ](https://github.com/apache/arrow-datafusion/issues/7014) 
* Anything that improves DataFusion's quality such as bug fixes, and improved / expanded tests, etc

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation or the projects named above. 

If you propose adding new functionality, especially if the PR is large/complex and not connected to a wider need, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example, the CI passes, includes documentation, etc)

## Background
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week (both for my future self and others)

**Comment by alamb** [comment]
Next week: https://github.com/apache/datafusion/issues/11710
