### ISSUE TITLE
[Epic] High cardinality aggregation performance wishlist

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11679]
### Is your feature request related to a problem or challenge?

This is my wishlist for improving high cardinality aggregates (ideally for the next blog post in a few months #11631 )

Together with the StringView work in https://github.com/apache/datafusion/issues/10918 that @XiangpengHao  @a10y and others are working on, I think it would provide some very compelling overall speedups in ClickBench and TPCH queries

### Describe the solution you'd like

Here is my wishlist:
- [ ] https://github.com/apache/datafusion/issues/6937 (@korowa  has a PR up for this one)
- [ ] https://github.com/apache/datafusion/issues/7957 (I have a prototype and some ideas) 
- [ ] TBF: reuse the hashed values (working on filing this)

### Describe alternatives you've considered

Do nothing and let DuckDB pass us by ;)

**Comment by alamb** [comment]
Bonus items:
- [ ] https://github.com/apache/datafusion/issues/11717 from @Rachelint

**Comment by alamb** [comment]
https://github.com/apache/datafusion/issues/6937 -- bam

**Comment by alamb** [comment]
Update here
- [x] https://github.com/apache/datafusion/pull/11627 -- improvement from @korowa  
- [x] https://github.com/apache/datafusion/pull/12269 -- improvement from @jayzhan211

**Comment by alamb** [comment]
Here is another great improvement: https://github.com/apache/datafusion/pull/12996
