### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - July 29, 2024

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11710]
Follow on to https://github.com/apache/datafusion/issues/11601

My (personal) North ⭐ : 1000 projects are built using DataFusion 📈 

**It would be great for other contributors to DataFusion to to make them visible somehow as well** 🙏  (feel free to copy / modify the format of this ticket)

## External news
* DataFusion 40.0.0 blog released: https://datafusion.apache.org/blog/2024/07/24/datafusion-40.0.0/

# Major Discussions (Please Take a Look)
* Logical Types: https://github.com/apache/datafusion/issues/11513 from @notfilippo 
* Roadmap discussion (TLDR; performance): https://github.com/apache/datafusion/issues/11442

## Upcoming Meetups
* https://github.com/apache/datafusion/discussions/11213
* https://github.com/apache/datafusion/discussions/11431

## Highlights last week
* Merged Split out catalog (and change `TableProvider`): https://github.com/apache/datafusion/pull/11516 from @findepi
* Updated to arrow 52.2.0: https://github.com/apache/datafusion/pull/11691
* @samuelcolvin started improving performance: https://github.com/apache/arrow-rs/issues/6107
* @korowa  created a 👌  PR to improve high cardinality aggregates https://github.com/apache/datafusion/pull/11627
* `CsvExecBuilder` from @connec : https://github.com/apache/datafusion/pull/11633
* Expr builders for Windows and Aggregate: https://github.com/apache/datafusion/pull/11550 (thanks @timsaucer and @jayzhan211)

## My (personal) plans for this week
- [ ] Help along performance projects (partial aggregation, string view)
- [ ] https://github.com/apache/datafusion/issues/7957
- [ ] Work down the review backlogs (arrow-rs backlog is going in the wrong direction 😭 ) 
- [ ] File follow on tickets for outstanding projects like https://github.com/apache/datafusion/issues/11567, and the physical optimizer move

## Projects I plan to help actively help review / push forward
- [ ] https://github.com/apache/arrow-rs/pull/6000 , with @etseidl and @adriangb
- [ ] High Cardinality Grouping: https://github.com/apache/datafusion/issues/11679
- [ ] User defined aggregates over the line (https://github.com/apache/datafusion/issues/8708) - thanks to @Rachelint and @jcsherin and @edmondop and @jayzhan211). I think we are 
- [ ] StringView integration -- we are very close (see https://github.com/apache/datafusion/pull/11667) with @XiangpengHao @a10y and others

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://projects.apache.org/committee.html?datafusion) who can and do review and merge PRs, so this is not the priorities of the project as a whole, just the approximate algorithm I use to prioritize my own time.

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (my employer)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs for other features I think are strategically important (See below)
5. Other new features / additions to functionality (note this is the lowest on purpose)

The top strategically important projects in my head are:
* Improved performance (with benchmarks -- this is higher in my mind now)
* Anything that improves DataFusion's quality such as bug fixes, and improved / expanded tests, etc
* Anything that makes it easier to use DataFusion as a user (docs, examples, better APIs, etc), including [Getting started guide for new users (who want to use DataFusion in their project) ](https://github.com/apache/arrow-datafusion/issues/7014) 

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation or the projects named above. 

If you propose adding new functionality, especially if the PR is large/complex and not connected to a wider need, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example, the CI passes, includes documentation, etc)

## Background
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week (both for my future self and others)

**Comment by alamb** [comment]
REview Queue:

arrow-rs
- [ ] Take kernel speed in arrow-rs: https://github.com/apache/arrow-rs/pull/6168
- [ ]  bytestrema split: https://github.com/apache/arrow-rs/pull/6159
- [ ]

**Comment by alamb** [comment]
Next week's plan: https://github.com/apache/datafusion/issues/11826
