### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - Aug 5, 2024

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11826]
Follow on to https://github.com/apache/datafusion/issues/11710

My (personal) North ⭐ : 1000 projects are built using DataFusion 📈 

**It would be great for other contributors to DataFusion to to make them visible somehow as well** 🙏  (feel free to copy / modify the format of this ticket)

## External news
* DataFusion 40 is now in ClickBench rankings: https://benchmark.clickhouse.com [thanks](https://github.com/apache/datafusion/issues/11567) to @pmcgleenon 

https://ossrank.com/p/1573-apache-arrow-datafusion

Here is a fun chart showing the growth of contributors over the last few years (before 2020 is somewhat skewed as the code as in the main arrow monoreop at that time

![Image](https://github.com/user-attachments/assets/a6f30627-e318-4653-b40f-94809c744714)

# Major Discussions (Please Take a Look)
* Logical Types: https://github.com/apache/datafusion/issues/11513 from @notfilippo 

## Upcoming Meetups
* https://github.com/apache/datafusion/discussions/11213
* https://github.com/apache/datafusion/discussions/11431

## Highlights last week
* After an epic amount of work, @edmondop, @jayzhan211 and others [migrated the last aggregate functions](https://github.com/apache/datafusion/pull/11013) (`min`/`max`) to user defined aggregates and removed the ["built in" aggregate distinction](https://github.com/apache/datafusion/issues/8708).
* We declared "success" on initial StringView implementation in [arrow-rs](https://github.com/apache/arrow-rs/issues/5374) and [DataFusion](https://github.com/apache/datafusion/issues/10918)
* We are now hard at work making StringView better / on by default, thanks to @xinlifoobar , @tshauck, @XiangpengHao, @a10y and others for starting us off strong there
* We merged the [first](https://github.com/apache/datafusion/pull/11718) from @Rachelint and  [second](https://github.com/apache/datafusion/pull/11627) from @korowa  of what I expect will be a series of performance improvements for ClickBench queries over the next few months
* @lewiszlw keeps pounding out features and improvements that improve the codebase ❤ 🧑‍🍳 
* @goldmedal made it possible to https://github.com/apache/datafusion/pull/11780

```rust
SELECT MAP {'a':1, 'b':2, 'c':3};
----
{a: 1, b: 2, c: 3}
```

## My (personal) plans for this week
- [ ] Continue to review and organize StringView: https://github.com/apache/datafusion/issues/11752
- [ ] Contribute to performance via: https://github.com/apache/datafusion/issues/7957
- [ ] Work down the review backlogs (arrow-rs backlog is still going in the wrong direction 😭 ) 
- [ ] File follow on tickets for outstanding projects like the physical optimizer move

## Projects I plan to help actively help review / push forward
- [ ] High Cardinality Grouping: https://github.com/apache/datafusion/issues/11679
- [ ] StringView integration https://github.com/apache/datafusion/issues/11752

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://projects.apache.org/committee.html?datafusion) who can and do review and merge PRs, so this is not the priorities of the project as a whole, just the approximate algorithm I use to prioritize my own time.

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (my employer)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs for other features I think are strategically important (See below)
5. Other new features / additions to functionality (note this is the lowest on purpose)

The top strategically important projects in my head are:
* Improved performance (with benchmarks -- this is high in my mind now)
* Anything that improves DataFusion's quality such as bug fixes, and improved / expanded tests, etc
* Anything that makes it easier to use DataFusion as a user (docs, examples, better APIs, etc), including [Getting started guide for new users (who want to use DataFusion in their project) ](https://github.com/apache/arrow-datafusion/issues/7014) 

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation or the projects named above. 

If you propose adding new functionality, especially if the PR is large/complex and not connected to a wider need, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example, the CI passes, includes documentation, etc)

## Background
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week (both for my future self and others)

**Comment by alamb** [comment]
REview Queue:

DataFusion
- [ ] https://github.com/apache/datafusion/pull/11792
- [ ] https://github.com/apache/datafusion/pull/11758
- [ ] https://github.com/apache/datafusion/pull/11683
- [ ] https://github.com/apache/datafusion/pull/11724
- [ ] https://github.com/apache/datafusion/pull/11456

arrow-rs
- [ ] https://github.com/apache/arrow-rs/pull/6180

sqlparser
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1360

**Comment by alamb** [comment]
PRs in need of review:

DataFusion
- [ ] https://github.com/apache/datafusion/pull/11456
- [ ] https://github.com/apache/datafusion/pull/11938
- [ ] https://github.com/apache/datafusion/pull/11933

Arrow
- [ ] https://github.com/apache/arrow-rs/pull/6201

**Comment by alamb** [comment]
Next week: https://github.com/apache/datafusion/issues/11986
