### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - Aug 12, 2024

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11986]
Follow on to https://github.com/apache/datafusion/issues/11826

My (personal) North ⭐ : 1000 projects are built using DataFusion 📈 
( I think we are getting close )

**It would be great for other contributors to DataFusion to to make them visible somehow as well** 🙏  (feel free to copy / modify the format of this ticket)

## External news
* DataFusion 41 was released: https://twitter.com/synnadahq/status/1823413102848639005 

# Major Discussions (Please Take a Look)
* Logical Types: https://github.com/apache/datafusion/issues/11513 from @notfilippo 
* `dfdb`: https://github.com/apache/datafusion/issues/11979

## Upcoming Meetups
* https://github.com/apache/datafusion/discussions/11213
* https://github.com/apache/datafusion/discussions/11431

## Highlights from last week
* @jayzhan211 [joined the PMC](https://lists.apache.org/thread/z944z7m4446kq4svwml12nyo44j6h5z7)
* @korowa [became a committer](https://lists.apache.org/thread/1p19k5y7b2fdxzjzffopfflgfhcsx2kg)
* DataFusion `41.0.0` was released: https://crates.io/crates/datafusion/41.0.0
* @tshauck organized a giant pile of tickets for supporting `StringView` https://github.com/apache/datafusion/issues/11790 and we are well on the way to closing them out
* @lewiszlw kept the momentum up moving physical optimizers to their own crate: https://github.com/apache/datafusion/pull/11945
* @haohuaijin finished up the last work for UDAFs: https://github.com/apache/datafusion/pull/11926
* @peter-toth kept making CSE better and faster: https://github.com/apache/datafusion/pull/11683
* @samuelcolvin is [making](https://github.com/apache/datafusion/pull/11876) [working](https://github.com/apache/datafusion/pull/11849) with intervals and sets a breeze
* @Rachelint has been hacking away with @jayzhan211 to improve performance such as https://github.com/apache/datafusion/pull/11802

## My (personal) plans for this week
- [ ] sql parser https://github.com/sqlparser-rs/sqlparser-rs/issues/1349
- [x] object store release https://github.com/apache/arrow-rs/issues/6121
- [ ] board report https://github.com/apache/datafusion/issues/10156
- [ ] Work down the review backlogs (arrow-rs backlog is still going in the wrong direction 😭 ) 
- [ ] File follow on tickets for outstanding projects like the physical optimizer move
- [ ] Work thorough review backlog for StringView: https://github.com/apache/datafusion/issues/11752
- [ ] Try and find time to contributed to performance via: https://github.com/apache/datafusion/issues/7957

## Projects I plan to help actively help review / push forward
- [ ] High Cardinality Grouping: https://github.com/apache/datafusion/issues/11679
- [ ] StringView integration https://github.com/apache/datafusion/issues/11752

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://projects.apache.org/committee.html?datafusion) who can and do review and merge PRs, so this is not the priorities of the project as a whole, just the approximate algorithm I use to prioritize my own time.

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (my employer)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs for other features I think are strategically important (See below)
5. Other new features / additions to functionality (note this is the lowest on purpose)

The top strategically important projects in my head are:
* Improved performance (with benchmarks -- this is high in my mind now)
* Anything that improves DataFusion's quality such as bug fixes, and improved / expanded tests, etc
* Anything that makes it easier to use DataFusion as a user (docs, examples, better APIs, etc), including [Getting started guide for new users (who want to use DataFusion in their project) ](https://github.com/apache/arrow-datafusion/issues/7014) 

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation or the projects named above. 

If you propose adding new functionality, especially if the PR is large/complex and not connected to a wider need, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example, the CI passes, includes documentation, etc)

## Background
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week (both for my future self and others)

**Comment by alamb** [comment]
Next week: https://github.com/apache/datafusion/issues/12066
