### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - Aug 19, 2024 + Sep 2, 2024

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#12066]
Follow on to https://github.com/apache/datafusion/issues/11986

My (personal) North ⭐ : 1000 projects are built using DataFusion 📈 
( Getting closer all the time )

**It would be great for other contributors to DataFusion to to make them visible somehow as well** 🙏  (feel free to copy / modify the format of this ticket)

## External news
* @XiangpengHao published a [video](https://www.youtube.com/watch?v=RVLshX6fbds) and [slides](https://drive.google.com/file/d/1Qqd8V6cfS9rSQ_-JrinasQJwI79qlUEV/view?usp=drive_link) about adding StringView to DataFusion

# Major Discussions (Please Take a Look)
* Logical Types: https://github.com/apache/datafusion/issues/11513 from @notfilippo 
* `dfdb`: https://github.com/apache/datafusion/issues/11979

## Upcoming Meetups
* https://github.com/apache/datafusion/discussions/11213
* https://github.com/apache/datafusion/discussions/11431

## Highlights from last week
* @jcsherin began the migration of BuiltInWindowFunctions to all UDFs: https://github.com/apache/datafusion/pull/12030
* @Rachelint has been hacking away with @jayzhan211 to improve performance such as https://github.com/apache/datafusion/pull/11943
* @korowa made the default CSV reader easier to https://github.com/apache/datafusion/pull/11919
* @davanbenz, @Lordworms, @dmitrybugakov kept up the momentum to add StringView support to all functions https://github.com/apache/datafusion/issues/11790
* @Kev1n8 and @XiangpengHao started making `substr` faster using properties of `StringView` https://github.com/apache/datafusion/pull/12044
* I am preparing for the next arrow-rs upgrade: https://github.com/apache/datafusion/pull/12032

## My (personal) plans for this week
- [ ] Prepare for the arrow-rs release
- [ ] Work thorough review backlog (focused on StringView, and other features): https://github.com/apache/datafusion/issues/11752
- [ ] board report https://github.com/apache/datafusion/issues/10156
- [ ] Work down the review backlogs

## Projects I plan to help actively help review / push forward
- [ ] High Cardinality Grouping: https://github.com/apache/datafusion/issues/11679
- [ ] StringView integration https://github.com/apache/datafusion/issues/11752

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://projects.apache.org/committee.html?datafusion) who can and do review and merge PRs, so this is not the priorities of the project as a whole, just the approximate algorithm I use to prioritize my own time.

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (my employer)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs for other features I think are strategically important (See below)
5. Other new features / additions to functionality (note this is the lowest priority on purpose)

The top strategically important projects in my head are:
* Improved performance (with benchmarks -- this is high in my mind now)
* Anything that improves DataFusion's quality such as bug fixes, and improved / expanded tests, etc
* Anything that makes it easier to use DataFusion as a user (docs, examples, better APIs, etc), including [Getting started guide for new users (who want to use DataFusion in their project) ](https://github.com/apache/arrow-datafusion/issues/7014) 

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation or the projects named above. 

If you propose adding new functionality, especially if the PR is large/complex and not connected to a wider need, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example, the CI passes, includes documentation, etc)

## Background
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week (both for my future self and others)

**Comment by alamb** [comment]
In need of review

DataFusion
- [ ] https://github.com/apache/datafusion/pull/11943
- [ ] https://github.com/apache/datafusion/pull/12044

**Comment by emgeee** [comment]
Wanted to flag that the next SF Datafusion meetup is currently scheduled for September 25h -- https://lu.ma/05lyf19h

**Comment by alamb** [comment]
Next week: https://github.com/apache/datafusion/issues/12336
