### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - Sep 2, 2024

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#12336]
Follow on to https://github.com/apache/datafusion/issues/12066

My (personal) North ⭐ : 1000 projects are built using DataFusion 📈 
( Getting closer all the time )

**It would be great for other contributors to DataFusion to to make them visible somehow as well** 🙏  (feel free to copy / modify the format of this ticket)

## External news
* demonstration of how uwheel is integrated into DataFusion https://uwheel.rs/post/datafusion_uwheel/ (@Max-Meldrum )
* integrating StringView into DataFusion part 1:  https://www.influxdata.com/blog/faster-queries-with-stringview-part-one-influxdb/

# Major Discussions (Please Take a Look)
* None at the moment

## Upcoming Meetups
* https://github.com/apache/datafusion/discussions/11213
* https://github.com/apache/datafusion/discussions/11431

## Highlights from last week
* Will return next week -- I was out for 1.5 weeks and am behind

## My (personal) plans for this week
- [ ] complete board report https://github.com/apache/datafusion/issues/10156
- [ ] Work down the review backlog

## Projects I plan to help actively help review / push forward
- [ ] StringView integration https://github.com/apache/datafusion/issues/11752
- [ ] High Cardinality Grouping: https://github.com/apache/datafusion/issues/11679

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://projects.apache.org/committee.html?datafusion) who can and do review and merge PRs, so this is not the priorities of the project as a whole, just the approximate algorithm I use to prioritize my own time.

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (my employer)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs for other features I think are strategically important (See below)
5. Other new features / additions to functionality (note this is the lowest priority on purpose)

The top strategically important projects in my head are:
* Anything that improves DataFusion's quality such as bug fixes, and improved / expanded tests, etc
* Anything that makes it easier to use DataFusion as a user (docs, examples, better APIs, etc), including [Getting started guide for new users (who want to use DataFusion in their project) ](https://github.com/apache/arrow-datafusion/issues/7014) 
* Improved performance (with benchmarks -- this is high in my mind now)

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation or the projects named above. 

If you propose adding new functionality, especially if the PR is large/complex and not connected to a wider need, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. break it into small PRs, ensure there are tests in sqllogictest for example, the CI passes, includes documentation, etc)

## Background
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week (both for my future self and others)

**Comment by alamb** [comment]
Review Queue

DataFusion
- [ ] dynamic file provider: https://github.com/apache/datafusion/pull/11035
- [ ] 

Arrow-rs

sqlparser-rs

**Comment by alamb** [comment]
Review queue Friday Sep 6

sqlparser-rs:
- [ ] Merge https://github.com/sqlparser-rs/sqlparser-rs/pull/1398

**Comment by alamb** [comment]
next week: https://github.com/apache/datafusion/issues/12391
