### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - Sep 9, 2024

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#12391]
Follow on to https://github.com/apache/datafusion/issues/12336

My (personal) North ⭐ : 1000 projects are built using DataFusion 📈 ( Getting closer all the time )

**It would be great for other contributors to DataFusion to to make them visible somehow as well** 🙏  (feel free to copy / modify the format of this ticket)

## External news
* 

# Major Discussions (Please Take a Look)
* What features should DataFusion have? https://github.com/apache/datafusion/issues/12357

## Upcoming Meetups
* San Francisco datafusion meetup on Wednesday September 25th https://lu.ma/05lyf19h
* https://github.com/apache/datafusion/discussions/11213
* https://github.com/apache/datafusion/discussions/11431

## Highlights from last week
* @eejbyfeldt improved performance of filtering with https://github.com/apache/datafusion/pull/12281  
* @2010YOUY01 began optimizing string functions by special casing ASCII https://github.com/apache/datafusion/pull/12356
* @haohuaijin fixed a regression in planning performance: https://github.com/apache/datafusion/pull/12305
* @sgrebnov @phillipleblanc and others have been making the SQL unparser better: https://github.com/apache/datafusion/pull/12331, etc
* @Dandandan  is making joins even better: https://github.com/apache/datafusion/pull/12348 
* Thanks to @devanbenz @wiedld , @Kev1n8 and others we are getting close to ready for StringView (e.g. https://github.com/apache/datafusion/pull/12281, https://github.com/apache/datafusion/pull/12224, https://github.com/apache/datafusion/pull/12044) 
* Updated to the latest arrow/parquet version: https://github.com/apache/datafusion/pull/12032
* @findepi  removed Expr::Sort (this was 2 weeks ago technically, but I didn't write one of these lists last week): https://github.com/apache/datafusion/pull/12177

## My (personal) plans for this week
- [x] complete board report https://github.com/apache/datafusion/issues/10156
- [x] Work down the review backlog

## Projects I plan to help actively help review / push forward
- [ ] StringView integration https://github.com/apache/datafusion/issues/11752
- [ ] Parquet Filtering: https://github.com/apache/datafusion/issues/4028
- [ ] High Cardinality Grouping: https://github.com/apache/datafusion/issues/11679

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://projects.apache.org/committee.html?datafusion) who can and do review and merge PRs, so this is not the priorities of the project as a whole, just the approximate algorithm I use to prioritize my own time.

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (my employer)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs for other features I think are strategically important (See below)
5. Other new features / additions to functionality (note this is the lowest priority on purpose)

The top strategically important projects in my head are:
* Anything that improves DataFusion's quality such as bug fixes, and improved / expanded tests, etc
* Anything that makes it easier to use DataFusion as a user (docs, examples, better APIs, cleaner code, etc), including [Getting started guide for new users (who want to use DataFusion in their project) ](https://github.com/apache/arrow-datafusion/issues/7014) 
* Improved performance (with benchmarks)

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation or the projects named above. 

If you propose adding new functionality, especially if the PR is large/complex and not connected to a wider need, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. break it into small PRs, ensure there are tests in sqllogictest for example, the CI passes, includes documentation, etc)

## Background
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week (both for my future self and others)

**Comment by alamb** [comment]
Review Queue

DataFusion (bugs / improvements)
- [ ] 

DataFusion (performance):
- [ ] https://github.com/apache/datafusion/pull/11827
- [ ] https://github.com/apache/datafusion/pull/11943
- [ ] https://github.com/apache/datafusion/pull/12269

DataFusion (new features, lower priority for me):
- [ ] https://github.com/apache/datafusion/pull/12266
- [ ] https://github.com/apache/datafusion/pull/12186
- [ ] https://github.com/apache/datafusion/pull/12225
- [ ] https://github.com/apache/datafusion/pull/12080
- [ ] https://github.com/apache/datafusion/pull/12295
- [ ] https://github.com/apache/datafusion/pull/11978

Arrow-rs
- [ ] https://github.com/apache/arrow-rs/pull/6288
- [ ] https://github.com/apache/arrow-rs/pull/6290
- [ ] https://github.com/apache/arrow-rs/pull/6336


sqlparser-rs
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1401

**Comment by emgeee** [comment]
Also have an upcoming SF datafusion meetup on Wednesday September 25th https://lu.ma/05lyf19h

**Comment by alamb** [comment]
> Also have an upcoming SF datafusion meetup on Wednesday September 25th https://lu.ma/05lyf19h

Thanks, sorry added it to the description

**Comment by alamb** [comment]
Next week: https://github.com/apache/datafusion/issues/12494
