### ISSUE TITLE
[EPIC] Easier extension configuration  SessionState / SessionConfig

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#12550]
### Is your feature request related to a problem or challenge?

Part of the [discussion of keeping the core more modular](https://github.com/apache/datafusion/issues/12357) is to move move functionality into "extension packages" to leverage DataFusion's extensibility APIs

Part of making extension packages compelling is ensuring it is easy / convenient to configure DataFusion to use these extensions. This will reduce the pressure for us to add more features to the core datafusion repo

As @matthewmturner and myself have been working on integrating some extension packages as part https://github.com/datafusion-contrib/datafusion-dft  I have come across some things that would make it easier to configure DataFusion

### Describe the solution you'd like

In general, I believe the [`SessionStateBuilder`](https://docs.rs/datafusion/latest/datafusion/execution/session_state/struct.SessionStateBuilder.html)  added by @Omega359 in https://github.com/apache/datafusion/pull/11403 is the obvious API to consolidate configuration

This ticket tracks various tickets for making it easier to use `SessionStateBuilder` to configure extensions

### Describe alternatives you've considered

- [x] https://github.com/apache/datafusion/issues/12394
- [x] https://github.com/apache/datafusion/issues/12551
- [x] https://github.com/apache/datafusion/issues/12552
- [x] https://github.com/apache/datafusion/issues/12553
- [x] https://github.com/apache/datafusion/issues/12554
- [x] https://github.com/apache/datafusion/issues/12555

**Comment by Omega359** [comment]
@alamb - this looks to be completed?
