### ISSUE TITLE
[EPIC] Schema metadata handling / bugs

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#12733]
### Is your feature request related to a problem or challenge?

As described by @wiedld on https://github.com/apache/datafusion/pull/12729

> A https://github.com/apache/datafusion/pull/11989 (and released in 42.0.0) has [added a check](https://github.com/apache/datafusion/blob/322d83526909ab44cfbe34b982d1a1c36a4dbe8f/datafusion/core/src/physical_planner.rs#L676) that the logical and physical plan input schemas (to an aggregate node) are the same.

This check fails for us in several different queries now downstream in InfluxDB and this ticket tracks the list of issues we found

### Issues
- [x] https://github.com/apache/datafusion/issues/12687
- [x] #12734
- [x] #12735
- [ ] https://github.com/apache/datafusion/issues/12736
- [x] https://github.com/apache/datafusion/pull/12951
- [x] https://github.com/apache/datafusion/issues/13010
- [x] https://github.com/apache/datafusion/issues/13190

**Comment by alamb** [comment]
@wiedld  has found several more issues:
- [ ] https://github.com/apache/datafusion/pull/12951
- [ ] https://github.com/apache/datafusion/pull/12954

**Comment by eejbyfeldt** [comment]
Found another issue that triggers a schema issue here: https://github.com/apache/datafusion/issues/13190

**Comment by alamb** [comment]
> Found another issue that triggers a schema issue here: #13190

Thanks -- added to the list

Note I now have added the config option to work around the issue in https://github.com/apache/datafusion/pull/13176 for anyone who hits these

**Comment by wiedld** [comment]
Found, and fixed, another schema issue here: https://github.com/apache/datafusion/pull/13305. Reproducer test cases are also included.

**Comment by alamb** [comment]
The subtasks are largely done , let's call this one done

**Comment by adriangb** [comment]
Found another one: https://github.com/apache/datafusion/pull/19335
