### ISSUE TITLE
[Epic] A Collection of Additional UTF8View support tickets

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#13504]
### Is your feature request related to a problem or challenge?

@Omega359  / @timsaucer  have found that there are still some functions / workloads that don't work with Utf8View. This ticket is an attempt to organize them

Tasks
- [x] https://github.com/apache/datafusion/issues/11911
- [x] https://github.com/apache/datafusion/issues/13568
- [x] https://github.com/apache/datafusion/issues/12752
- [ ] https://github.com/apache/datafusion/pull/13370
- [ ] https://github.com/apache/datafusion/pull/13366
- [x] https://github.com/apache/datafusion/pull/13407
- [ ] https://github.com/apache/datafusion/issues/13408
- [x] https://github.com/apache/datafusion/pull/13221
- [x] https://github.com/apache/datafusion/issues/13379
- [x] https://github.com/apache/datafusion/issues/13330
- [x] https://github.com/apache/datafusion/pull/13403
- [x] https://github.com/apache/datafusion/issues/13360
- [x] https://github.com/apache/datafusion/pull/13346

**Comment by Omega359** [comment]
Related arrow-rs tickets:

- https://github.com/apache/arrow-rs/issues/6734
- https://github.com/apache/arrow-rs/issues/6714
- https://github.com/apache/arrow-rs/issues/6713

**Comment by alamb** [comment]
I will put those on my list to review shortly

**Comment by alamb** [comment]
Update here is that many of these remaining issues seem to be waiting on an upgrade to arrow-rs. Hopefully we'll get a fix out in the next week or two

**Comment by alamb** [comment]
BTW these items can be worked around if you disable the following config setting:

https://datafusion.apache.org/user-guide/configs.html

> datafusion.execution.parquet.schema_force_view_types

**Comment by alamb** [comment]
I think we have merged all the needed fixes for 45 so closing this PR
