### ISSUE TITLE
Automatically check "invariants"

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#13652]
### Is your feature request related to a problem or challenge?

I extracted this from https://github.com/apache/datafusion/pull/13651 so it was more visible

- Part of https://github.com/apache/datafusion/issues/13648
- Inspired by / copied from https://github.com/apache/datafusion/pull/13651 from @wiedld 

During upgrade, downstream systems often experience issues due to implicit changes (not explicit API changes) of LogicalPlans that DataFusion code begins relying on, and which result in unintended consequences when upgrading to a new version of DataFusion (see https://github.com/apache/datafusion/issues/13525). 

### Describe the solution you'd like

The idea is to make the current implicit assumptions ("Invariants" in more formal language)( explict and automatically check them. 

Examples of implicit assumptions:
1. Schema column names can't be repeated (this is explicitly mentioned on https://github.com/apache/datafusion/issues/13525)
2. Inputs to `UnionExec` must have the same schema
3. ...

### Describe alternatives you've considered

I like the  approach @wiedld took in https://github.com/apache/datafusion/pull/13651 :
* define the invariants
* check the invariants for extensible interfaces (which may be user defined)
* throw the error closer to the problem (rather than weird behavior later)

### Additional context

Sub tasks:
 - [x]  Define infrastructure to check LP invariant. PR: [Introduce LogicalPlan invariants, begin automatically checking them #13651](https://github.com/apache/datafusion/pull/13651)
- [ ]  Define infrastructure to check physical plan invariants: [WIP: Proposed interface for physical plan invariant checking. #13986](https://github.com/apache/datafusion/pull/13986)
- [ ]  Define infrastructure for user-defined invariants. See issue: https://github.com/apache/datafusion/issues/14029

**Comment by wiedld** [comment]
take

**Comment by wiedld** [comment]
### Possible tasks
- [x] Define when to check LP invariant. PR: https://github.com/apache/datafusion/pull/13651
- [ ] Define when to check physical plan invariants.
- [ ] Explore possible API for user-defined invariants, and potential use cases with user-defined plan elements (e.g. physical plan nodes, analyzer and optimizer rules, etc). Refer to [conversation here.](https://github.com/apache/datafusion/pull/13651#discussion_r1874536239)
- [ ] Consider options (e.g. generate of docs) to align the published docs with the invariants encoded.
- [ ] Implement more invariants.

**Comment by wiedld** [comment]
For the [physical optimization](https://docs.rs/datafusion/43.0.0/datafusion/physical_optimizer/trait.PhysicalOptimizerRule.html) invariants, we have that the [output physical plan schema cannot change](https://datafusion.apache.org/contributor-guide/specification/invariants.html#physical-schema-is-invariant-under-physical-optimization); meaning the output results cannot change, but how we get the results can.

What else should be included as a responsibility/check?

**Comment by alamb** [comment]
> For the [physical optimization](https://docs.rs/datafusion/43.0.0/datafusion/physical_optimizer/trait.PhysicalOptimizerRule.html) invariants, we have that the [output physical plan schema cannot change](https://datafusion.apache.org/contributor-guide/specification/invariants.html#physical-schema-is-invariant-under-physical-optimization); meaning the output results cannot change, but how we get the results can.
> 
> What else should be included as a responsibility/check? Maintain input ordering if required?

Here are some ideas based on bugs we have hit / my memory of what has changed and caused us pain:
1. Union inputs (can there be more than 2 inputs -- we use such plans in InfluxData but I am not sure what if anything else makes assumptions)
2. Union input schemas  (I think initially they need to be 'coercable' and to be executable they need to be identical)
3. Projection_exec can't have zero exprs (is this an invariant?)

**Comment by wiedld** [comment]
My impression was that the plan construction occurred with the LP (as we do), and not by constructing their own de novo physical plan. Is this correct?

If so, then I think the [above list of invariants](https://github.com/apache/datafusion/issues/13652#issuecomment-2563115493) to check would most likely occur at the LP-level (not the physical plan). I can definitely put up a PR for those. Thank you!

Whereas for the physical plan invariants, (not LP), do we want any invariant checking there? Because I looked at the apache docs & physical plan APIs and from (my naive) understanding [these are the only two invariants](https://github.com/apache/datafusion/issues/13652#issuecomment-2563033771) to check after physical plan mutations (a.k.a. PhysicalOptimizerRule applied). Is this correct? 🤔

**Comment by alamb** [comment]
> My impression was that the plan construction occurred with the LP (as we do), and not by constructing their own de novo physical plan. Is this correct?

I am sorry -- I don't understand what you are asking (is LP LogicalPlan?) What does a de novo physical plan mean? You mean like creating a `ExecutionPlan` directly (not from a `LogicalPlan`)?

> 
> If so, then I think the [above list of invariants](https://github.com/apache/datafusion/issues/13652#issuecomment-2563115493) to check would most likely occur at the LP-level (not the physical plan). I can definitely put up a PR for those. Thank you!



> 
> Whereas for the physical plan invariants, (not LP), do we want any invariant checking there? Because I looked at the apache docs & physical plan APIs and from (my naive) understanding [these are the only two invariants](https://github.com/apache/datafusion/issues/13652#issuecomment-2563033771) to check after physical plan mutations (a.k.a. PhysicalOptimizerRule applied). Is this correct? 🤔

I am not sure what the actual invariants are (part of this project I think is to discover that information)

In my opinion we should be seeking to discover what the existing implicit assumptions are and encode them explicitly in the invariant check. Once we have all the existing assumptions encoded then we can move on to trying to add more assumptions

**Comment by alamb** [comment]
I just discovered that @houqp  basically filed this same ticket 2 years ago:
- https://github.com/apache/datafusion/issues/594

**Comment by alamb** [comment]
I suggest we use this ticket to track the infrastructure for checking invariants (e.g. what @wiedld is doing in https://github.com/apache/datafusion/pull/13986) and then claim success.

We can introduce additional invariant checks as we discover them

**Comment by wiedld** [comment]
> I suggest we use this ticket to track the infrastructure for checking invariants

Agreed. Modifying [this list above](https://github.com/apache/datafusion/issues/13652#issuecomment-2550443777), we have infrastructure components of:

 - [x]  Define infrastructure to check LP invariant. PR: [Introduce LogicalPlan invariants, begin automatically checking them #13651](https://github.com/apache/datafusion/pull/13651)

- [ ]  Define infrastructure to check physical plan invariants: [WIP: Proposed interface for physical plan invariant checking. #13986](https://github.com/apache/datafusion/pull/13986)

- [ ]  Define infrastructure for user-defined invariants. See issue: TODO

**Comment by alamb** [comment]
Task complete!
