### ISSUE TITLE
[EPIC] A collection of items to improve developer / CI speed 

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#13813]
### Is your feature request related to a problem or challenge?

As DataFusion becomes more mature and gets more features and tests, the amount of time it takes to build and test the system has been increasing

This has several downsides:
## Barrier to new contributors is higher

The resources required to build / link DataFusion are now very large which means some people may not be able to run them. For example @Alexhuszagh reports on https://github.com/apache/datafusion/pull/13693#issuecomment-2526394913

> I only tested this locally with the failing datasource::physical_plan::json::tests::test_chunked_json tests, but it should be the same with all the remaining errors. My test machine doesn't have enough RAM to link the entire core test suite,

## We are likely wasting lots of resources running CI tests 
By my count the CI checks on the most recent checkin ([link](https://github.com/apache/datafusion/pull/13797/checks)) require over 200 hours of runner time

We are lucky the ASF gets many runner credits from github, but this level is very wasteful in my opinion and likely unsustainable as we contemplate adding additional testing such as
- https://github.com/apache/datafusion/issues/13812

## Larger binary size
I have noticed that the datafusion-cli binary is now almost 100MB it used to be 60MB

Also, people such as @g3blv have noticed that the WASM build has increased 50%:
https://github.com/apache/datafusion/discussions/9834#discussioncomment-11574581

See
 - https://github.com/apache/datafusion/issues/13816

## Decreased developer productivity due to longer cycle times
As DataFusion gets bigger, I have noticed that recompiling datafusion for me takes longer and longer

cargo test ...

### Describe the solution you'd like

I would like to make the building and testing of DataFusion "easier"  and leaner. This ticket tracks work to improve things in this area

### Describe alternatives you've considered

- [ ] https://github.com/apache/datafusion/issues/13726
- [ ] https://github.com/apache/datafusion/issues/13814
- [x] https://github.com/apache/datafusion/issues/13816
- [ ] https://github.com/apache/datafusion/issues/11105
- [x] https://github.com/apache/datafusion/issues/13846
- [x] https://github.com/apache/datafusion/issues/13845

**Comment by Alexhuszagh** [comment]
If this could be improved it would be wonderful. Arrow and Datafusion are very important projects using lexical and I want to test all my code against them and other high impact projects as an additional precaution in addition to our own checks internally, so being able to run these tests locally would be a huge benefit on my end.

**Comment by Omega359** [comment]
Is there a way to test changes to the ci pipeline without actually checking in files to DF?

**Comment by alamb** [comment]
> Is there a way to test changes to the ci pipeline without actually checking in files to DF?

We could in theory change the triggering rules for the the jobs to run on any changes to `.github` as well

**Comment by Omega359** [comment]
If no one beats me to this I can likely take a look at the ci pipeline during the holiday break. I still want to finish the sqlite test integration first if possible though.

**Comment by alamb** [comment]
I also hope to hack on various parts of this EPIC during thebreak

**Comment by findepi** [comment]
> Is there a way to test changes to the ci pipeline without actually checking in files to DF?

@Omega359 you can enable the workflow(s) on your fork

**Comment by Omega359** [comment]
I've managed to knock some time off of the ci runs on a sidebranch (need to rebase off of main before pushing a PR) bu here is what I've managed to get to so far:

an example of a PR run now:
![image](https://github.com/user-attachments/assets/c9f0cb07-e69e-4f08-bd3b-1f9efc419026)

my sidebranch on the second run (cache populated)
![image](https://github.com/user-attachments/assets/9d79c863-f380-4dc8-a297-4045bc1b41a7)

cargo test doc and hash collisions are the two ones right now that take the most time and much of that is DF compilation that can't really be cached (would blow out the 10GB cache limit I think).

Most of the improvement is better caching, splitting up the linux build test into multiple jobs (it's all cargo checks), and switching to nextest for many tests. I also disabled the intel mac build test.

I hope to submit a PR this weekend for this.

**Comment by alamb** [comment]
> I've managed to knock some time off of the ci runs on a sidebranch (need to rebase off of main before pushing a PR) but here is what I've managed to get to so far:


LOL your screenshots show 37m --> 19m (which is a 2x improvement by my accounting) so that is a somewhat modest description :)


> cargo test doc and hash collisions are the two ones right now that take the most time and much 

I think the hash collisions one fails so irregularly, that we should consider simply running it on main (not on all PRs) as discussed in https://github.com/apache/datafusion/issues/13845. While that does indeed defer the potential for finding issues I think the tradeoff might be worth it in this specific case

**Comment by Omega359** [comment]
FYI, I came across [this today](https://github.com/rust-lang/rust/pull/126245) with a great example of how much faster doctests can be in [this comment](https://github.com/rust-lang/rust/pull/126245#issuecomment-2291429124). 2024 edition though...

**Comment by findepi** [comment]
good find!

> 2024 edition though...

but maybe it's not a bad thing? https://doc.rust-lang.org/edition-guide/editions/#editions-do-not-split-the-ecosystem

**Comment by Omega359** [comment]
> good find!
> 
> > 2024 edition though...
> 
> but maybe it's not a bad thing? https://doc.rust-lang.org/edition-guide/editions/#editions-do-not-split-the-ecosystem

I tried to compile DF under nightly with 2024 edition ... there are quite a few code changes that will have to be made. #1 is rng.gen => rng.r#gen (gen is now a reserved keyword). #2 is 
```
error: this pattern relies on behavior which may change in edition 2024
   --> datafusion/proto-common/src/from_proto/mod.rs:443:49
    |
443 |                         DataType::Dictionary(_, ref value_type) => {
    |                                                 ^^^ cannot override to bind by-reference when that is the implicit default
    |
    = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/match-ergonomics.html>
help: make the implied reference pattern explicit
    |
443 |                         &DataType::Dictionary(_, ref value_type) => {
    |                         +
```

**Comment by blaginin** [comment]
Added cache to CI runners to get some speedup: https://github.com/apache/datafusion/pull/16709

Also pinged the infra team if we can get larger runners: https://issues.apache.org/jira/browse/INFRA-27000

**Comment by blaginin** [comment]
For transparency: we want to try the merge queue https://github.com/apache/datafusion/issues/6880

> I also pinged the infra team to see if we can get larger runners

The infra team said they are not available now. I believe there's a discussion about providing more powerful runners, but no decisions have been made yet.

I also chatted with the Apache Fundraising team - it's possible to submit a "need" we have (=compute for large runners), so if a company is ever willing, ASF will match us. Happy to manage the process on our side if there any no objections?
