### ISSUE TITLE
support cast to decimal data type in datafusion

### ISSUE THREAD

**Issue by liukun4515** [apache/datafusion#1443]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
In the #122 , we need to support the decimal data type.

In order to support `column_a > 12` for the decimal data type, we need to support the cast/try_cast first.
For some operations, such as comparison operations and mathematics operations, we need to convert some numeric data types to decimal first.

**TODO**
- [x] signed numeric to decimal https://github.com/apache/arrow-datafusion/pull/1442
- [x] utf-8 to decimal #3478
- [x] decimal to signed numeric https://github.com/apache/arrow-datafusion/pull/1465
- [x] remove duplicated code for cast/try_cast code  https://github.com/apache/arrow-datafusion/pull/1465#pullrequestreview-853170945
- [x] decimal to diff decimal https://github.com/apache/arrow-datafusion/pull/1603

The unsigned numeric is not the standard data type in SQL, we no need to support them. @alamb 

Some parts in arrow-rs: https://github.com/apache/arrow-rs/issues/1043

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by liukun4515** [comment]
please assign this issue to me.

**Comment by Jefffrey** [comment]
Looks like all mentioned TODOs are done so closing this

**Comment by alamb** [comment]
🎉
