### ISSUE TITLE
[EPIC] Improved support for nested / structured types (`Struct` , `List`, `ListArray`, and other Composite types)

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#2326]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
This ticket is designed to capture the work needed to properly support Arrow `Struct` types in DataFusion

https://arrow.apache.org/datafusion/user-guide/sql/sql_status.html says that nested types are not supported; The are not fully supported, but there are parts of the support already present such as a way to serialize them via ArrowWriter and using `field["nested_field"]` syntax

**Describe the solution you'd like**
Research, and describe / implement what is else remains for proper support. 

## Array (`ListArray`) support:
- [x] https://github.com/apache/arrow-datafusion/issues/6980
- [x] https://github.com/apache/arrow-datafusion/issues/6560
- [x] https://github.com/apache/arrow-datafusion/issues/6555
- [ ] #9252

## Map (`MapArray`) support:
- [x] https://github.com/apache/datafusion/issues/11429

## Struct (`StructArray`) support:
- https://github.com/apache/arrow-datafusion/issues/5861
- https://github.com/apache/arrow-datafusion/issues/9820
- #10207 
- https://github.com/apache/datafusion/issues/10264
- https://github.com/apache/datafusion/issues/10660
- #11204 
- https://github.com/apache/datafusion/issues/11438
- https://github.com/apache/datafusion/issues/11445

## Union (`UnionArray`) support
- #10206 

## Other

Known issues so far:
- [x]  https://github.com/apache/arrow-datafusion/issues/2179 from @Cheappie
- [x] https://github.com/apache/arrow-datafusion/issues/2043 from @lquerel 
- [ ] https://github.com/apache/arrow-datafusion/issues/3617 from @kesavkolla
- [ ] https://github.com/apache/arrow-datafusion/issues/6074
- [ ] https://github.com/apache/arrow-datafusion/issues/1222
- [ ] https://github.com/apache/arrow-datafusion/issues/2581
- [x] https://github.com/apache/arrow-datafusion/discussions/6446
- [x] https://github.com/apache/arrow-datafusion/issues/6075
- [x] https://github.com/apache/arrow-datafusion/issues/6119
- [x] https://github.com/apache/arrow-datafusion/issues/6561
- [x] https://github.com/apache/arrow-datafusion/issues/6556
- [x] https://github.com/apache/arrow-datafusion/issues/6557
- [ ] https://github.com/apache/arrow-datafusion/issues/6559
- [x] https://github.com/apache/arrow-datafusion/issues/6603
- [ ] https://github.com/apache/arrow-datafusion/issues/6602
- [x] https://github.com/apache/arrow-datafusion/issues/6598
- [ ] https://github.com/apache/arrow-datafusion/issues/6631
- [ ] https://github.com/apache/arrow-datafusion/issues/3617
- [x] https://github.com/apache/arrow-datafusion/issues/6743
- [ ] https://github.com/apache/arrow-datafusion/issues/7012
- [ ] https://github.com/apache/arrow-datafusion/issues/8334
- [ ] https://github.com/apache/datafusion/issues/11746

**Comment by nl5887** [comment]
This https://github.com/apache/arrow-datafusion/blob/master/datafusion/core/src/physical_plan/file_format/mod.rs#L238 is one reason of errors related to column projection. It compares the complete enum, failing on different filed order.

**Comment by alamb** [comment]
Thanks for the investigation @nl5887  -- that sounds definitely plausible. Feel free to file a PR with proposed changed -- we would love to review them

**Comment by nl5887** [comment]
This one is also related: https://github.com/apache/arrow-datafusion/issues/2581

**Comment by tv42** [comment]
Reminder to write docs: #1222

**Comment by alexwilcoxson-rel** [comment]
Potential to add to list #7012

**Comment by alamb** [comment]
We are starting to make progress on struct support --

There is a PR up to support `named_struct` https://github.com/apache/arrow-datafusion/pull/9743 and work afoot to support nicer literal syntax: https://github.com/apache/arrow-datafusion/issues/9820 🚀

**Comment by toaiduongdh** [comment]
Hi, i think unnest support for struct can be an item in this epic right?

**Comment by alamb** [comment]
> Hi, i think unnest support for struct can be an item in this epic right?

That would make sense to me -- is there a ticket that describes what this means? I

**Comment by duongcongtoai** [comment]
i created a ticket: https://github.com/apache/datafusion/issues/10264

**Comment by alamb** [comment]
> i created a ticket: #10264

Thank you. I added this to the list in the ticket description

**Comment by duongcongtoai** [comment]
I added an issue to support recursive unnest: https://github.com/apache/datafusion/issues/10660

**Comment by alamb** [comment]
> I added an issue to support recursive unnest: #10660, i think it shoul belong to this epic

Added

**Comment by goldmedal** [comment]
I added an issue to check the duplicate or null name for struct: https://github.com/apache/datafusion/issues/11438

**Comment by Throne3d** [comment]
I think #11445 is related to this epic

**Comment by alamb** [comment]
> I think #11445 is related to this epic

Thank you -- added

**Comment by TheBuilderJR** [comment]
Right now datafusion doesn't support struct evolution very well. Imagine you have a struct named `customData` with field `someOptionEnabled` in one parquet file, later down the line you add a new field `newAddedOption` to the `customData` struct in another parquet file. Currently when you try and `SELECT * FROM table` you'll get this error:

```
{"message":"Failed to collect DataFrame batches: Plan(\"Cannot cast file schema field customData of type Struct([Field { name: \\\"someOptionEnabled\\\", data_type: Boolean, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }]) to table schema field of type Struct([Field { name: \\\"someOptionEnabled\\\", data_type: Boolean, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: \\\"newAddedOption\\\", data_type: Float64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }])\")","status":"error"}
```

Feels like we should handle this more gracefully. cc @alamb 

I'm happy to make contributions if someone can point me to the right places to look.

**Comment by alamb** [comment]
> Right now datafusion doesn't support struct evolution very well. Imagine you have a struct named `customData` with field `someOptionEnabled` in one parquet file, later down the line you add a new field `newAddedOption` to the `customData` struct in another parquet file. Currently when you try and `SELECT * FROM table` you'll get this error:
> 
> ```
> {"message":"Failed to collect DataFrame batches: Plan(\"Cannot cast file schema field customData of type Struct([Field { name: \\\"someOptionEnabled\\\", data_type: Boolean, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }]) to table schema field of type Struct([Field { name: \\\"someOptionEnabled\\\", data_type: Boolean, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: \\\"newAddedOption\\\", data_type: Float64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }])\")","status":"error"}
> ```
> 
> Feels like we should handle this more gracefully. cc @alamb

I agree

> I'm happy to make contributions if someone can point me to the right places to look.

My suggestion is to start with filing a ticket with a self contained reproducer (either rust code or SQL) that shows what you are trying to do.

This would likely become part of the test of any code improvement we make, as well as providing some more detail for other contributors to help point to the right place in the code

**Comment by alamb** [comment]
I think we will claim datafusion has pretty good structured type support now, so let's close this epic and treat additional work as new issues / items

**Comment by TheBuilderJR** [comment]
@alamb I just tried this on 45.0 and it still doesn't seem supported:

```
 Failed to collect data frame results: Plan("Cannot cast file schema field additionalInfo of type Struct([Field { name: \"location\", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: \"timestamp_utc\", data_type: Timestamp(Millisecond, Some(\"UTC\")), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }]) to table schema field of type Struct([Field { name: \"location\", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: \"timestamp_utc\", data_type: Timestamp(Millisecond, Some(\"UTC\")), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: \"reason\", data_type: Struct([Field { name: \"_level\", data_type: Float64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: \"details\", data_type: Struct([Field { name: \"rurl\", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: \"s\", data_type: Float64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: \"t\", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }]), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }]), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }])
```

Do I need to flip a flag or something?

![Image](https://github.com/user-attachments/assets/db8dfbd3-9b1d-470a-8738-a719834e92d4)

**Comment by TheBuilderJR** [comment]
Filed an issue here: https://github.com/apache/datafusion/issues/14757
