### ISSUE TITLE
[EPIC] Add Decimal support

### ISSUE THREAD

**Issue by liukun4515** [apache/datafusion#3523]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

I have implemented the feature about decimal in the datafusion. But didn't take care about some special case.
Specially when do the arithmetic operation: 
1. loss of the precision, In many case, the intermediate result will be overflow, So we use the float32 or float64 as the intermediate which will cause the the issue of loss of precision
2. overflow/out of the range

Correctness Issues:
- [x] https://github.com/apache/arrow-datafusion/issues/4035
- [x] https://github.com/apache/arrow-datafusion/issues/3521
- [x] https://github.com/apache/arrow-datafusion/issues/2259

NULL cast/ NULL arithmetic/NULL comparator
- [x] https://github.com/apache/arrow-datafusion/issues/3487

String cast:
- [x] https://github.com/apache/arrow-datafusion/issues/3478

AGG decimal
- [ ] https://github.com/apache/arrow-datafusion/issues/3481

User Experience:
- [x] https://github.com/apache/arrow-datafusion/issues/3498
- [ ] https://github.com/apache/arrow-datafusion/issues/3666

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by liukun4515** [comment]
cc @liukun4515 @kmitchener

**Comment by kmitchener** [comment]
Thanks @liukun4515. It's all the issues listed in #3480 as well:

* #3437
* #3479 

Per other discussions, I'd like to help here. I think the general plan should be something like:

* stabilize and add tests
* move the decimal implementation code to arrow-rs
* have the discussion about Decimal128/256 implementation that's going on arrow-rs and agree on path forward for implementation details
* meanwhile in DataFusion, continue to improve use of Decimals in the math functions, sql literals, scientific notation support, etc.

I think there will be some churn .. for example, to fix #3521 , we could use the `num` crate that arrow-rs already uses and fix the implementation of the decimal divide method here. However, that's only a fine short-term solution for stabilization and we'd need to remove the `num` crate again when we finally move the Decimal kernel implementation over to arrow-rs. Is that acceptable?

Also, how do you deal with the synchronization between the projects? for example, some DF issues are due to the decimal cast code in arrow-rs .. how do we test the fixes? now that we're at the beginning of the dev cycle for 13, can we change DF to pin it to arrow-rs git revs?

cc @alamb

**Comment by kmitchener** [comment]
Hm, I see the situation in arrow-rs is complicated re decimals and I want to retract all opinions at this time. :)

**Comment by liukun4515** [comment]
> Also, how do you deal with the synchronization between the projects? for example, some DF issues are due to the decimal cast code in arrow-rs .. how do we test the fixes? now that we're at the beginning of the dev cycle for 13, can we change DF to pin it to arrow-rs git revs?

Hi @kmitchener 

I think we can resolve the arithmetic operation for decimal128 data type in this sprint, I will do this and move the operation to the arrow-rs.

At the same time, I will fix the issue about decimal in datafusion. From the bug issue list, I think the most issue about decimal operation in the datafusion are about the `divide` arithmetic operation.

And other issue is about feature, like casting between string and decimal which can be implement in the arrow-rs.

**Comment by liukun4515** [comment]
@kmitchener  if the casting feature is important for you, it's great to add it in the arrow-rs kernel.

**Comment by alamb** [comment]
> Also, how do you deal with the synchronization between the projects? for example, some DF issues are due to the decimal cast code in arrow-rs .. how do we test the fixes? now that we're at the beginning of the dev cycle for 13, can we change DF to pin it to arrow-rs git revs?

@kmitchener  I have seen two basic patterns for this:
1. Make a PR that pins to a arrow-rs git revision and complete the changes you want (and this basically leaves the PR as a draft for a while). Example: https://github.com/apache/arrow-datafusion/pull/3386
2. Make a "wrapper" / "adapter" function for the arrow one, adding whatever new special logic is needed and calling into the arrow kernel if needed. For example https://github.com/apache/arrow-datafusion/blob/master/datafusion/physical-expr/src/expressions/binary/adapter.rs

**Comment by kmitchener** [comment]
@liukun4515 I'll submit a couple PRs to move the decimal kernels to arrow-rs. I have the code moved locally and it's mostly working -- enough that I'm confident I can complete it.

**Comment by liukun4515** [comment]
> I'll submit a couple PRs to move the decimal kernels to arrow-rs. I have the code moved locally and it's mostly working -- enough that I'm confident I can complete it.

I think it is not easy work to move the decimal operation to arrow-rs.
We can not do the comparation and arithmetic operation based on the I128, we should support the decimal256 also.
I try it in my local, it works.
But We need do more work to make it grace, there are some pr about decimal in the arrow-rs you can take a look it.

**Comment by kmitchener** [comment]
@liukun4515 @alamb Here are the 2 PRs. The one for arrow-rs is ready for review. The one for DF will remain in draft until arrow-rs 24 is released.

https://github.com/apache/arrow-rs/pull/2770
https://github.com/apache/arrow-datafusion/pull/3590

If/once https://github.com/apache/arrow-rs/pull/2770 is merged in, I'll update the DF PR to use git revs.

**Comment by alamb** [comment]
I wonder if we should claim this ticket is complete? I wonder if there is anything else this ticket is tracking

**Comment by liukun4515** [comment]
> I wonder if we should claim this ticket is complete? I wonder if there is anything else this ticket is tracking

I will check above unclosed issue in this week.

**Comment by alamb** [comment]
I think I am going to claim this epic is complete and that DataFusion supports decimals. We can track additional work in other tickets if needed

**Comment by lostmygithubaccount** [comment]
just noting this page still says it's experimental: https://datafusion.apache.org/user-guide/sql/data_types.html

**Comment by alamb** [comment]
Thanks @lostmygithubaccount  -- I made a ticket to fix that:
- https://github.com/apache/datafusion/issues/15464

**Comment by niebayes** [comment]
This https://github.com/apache/arrow-rs/issues/7343 might help write tests involving decimal data type.
