### ISSUE TITLE
[Epic] Improved DataFusion Benchmarking

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#5505]
# Call to action:

Let's invest more effort in DataFusion benchmarking, both as a mechanism for technical evangelism as well as a guide for actual performance improvements. 

# Background

We have several examples of performance “comparisons” showing DataFusion not doing well against DuckDB or pola.rs that really was a test of how fast CSV or JSON parsing can go ([this blog ](https://www.confessionsofadataguy.com/dataframe-showdown-polars-vs-spark-vs-pandas-vs-datafusion-guess-who-wins/)is one such example) – recent work should make these comparisons much more favorable in the future

It is in the interest of all projects based on DataFusion to focus on their own users and use cases rather than having to explain why they are using supposedly "inferior" technology due to misleading benchmark results (for example recently on ClickBench – see https://github.com/apache/arrow-datafusion/issues/5276).

Of course not only will improved benchmarking help evangelize DataFusion more, it will also directly help guide the community’s optimization efforts.

# Related Tickets

- [x] https://github.com/apache/arrow-datafusion/issues/5502
- [ ]  https://github.com/apache/arrow-datafusion/issues/5504
- [x] https://github.com/apache/arrow-datafusion/issues/5276
- [ ] https://github.com/apache/arrow-datafusion/issues/6156
- [ ] https://github.com/apache/arrow-datafusion/issues/4032
- [x] https://github.com/apache/arrow-datafusion/issues/5561
- [x] https://github.com/apache/arrow-datafusion/issues/5942
- [x] #6127
- [x] https://github.com/apache/arrow-datafusion/issues/6128
- [x] https://github.com/apache/arrow-datafusion/issues/5404
- [x] https://github.com/apache/arrow-datafusion/issues/5969
- [x] https://github.com/apache/arrow-datafusion/issues/6584

**Comment by comphead** [comment]
@alamb 5276 included twice

**Comment by jackwener** [comment]
> @alamb 5276 included twice

Thanks remind, I have removed it.

**Comment by alamb** [comment]
Here is a proposed PR to orchestrate running the benchmarks: https://github.com/apache/arrow-datafusion/pull/6131

**Comment by alamb** [comment]
I think this epic is basically done and we can track follow on items as other projects / tickets
