### ISSUE TITLE
[Epic] General ticket for the concept of the practical implementation of `ARRAY`

### ISSUE THREAD

**Issue by izveigor** [apache/datafusion#6980]
### Is your feature request related to a problem or challenge?

It was decided that further development of array functions will be carried out according to the following concept: https://github.com/apache/arrow-datafusion/discussions/6855.
According to the concept, any changes may be subject to rational criticism, so some aspects may change.
It should be noted that this list is incomplete and will be updated in the future.
The ticket contains many tickets. Each ticket is divided into respective categories:

# List of features

A complete list of features, the implementation of which is desirable from the point of view of this concept 🎯:

## Cleanups
- [x] https://github.com/apache/arrow-datafusion/issues/7988

### By index:

- [x] `array_element` https://github.com/apache/arrow-datafusion/issues/6974
- [x] `array_slice` https://github.com/apache/arrow-datafusion/issues/6975

### By borders:

- [x] `array_pop_front` https://github.com/apache/arrow-datafusion/issues/6996
- [x] `array_pop_back` https://github.com/apache/arrow-datafusion/issues/6997

### Dimension

- [x] `flatten` https://github.com/apache/arrow-datafusion/issues/6995

### Basic operations on sets:

- [x] https://github.com/apache/arrow-datafusion/issues/6981
- [x] https://github.com/apache/arrow-datafusion/issues/6978
- [x] https://github.com/apache/arrow-datafusion/issues/6979

### Checking if elements belong:

- [x] `array_has_all` https://github.com/apache/arrow-datafusion/issues/6973
- [x] `array_has_any` https://github.com/apache/arrow-datafusion/issues/6976
- [x] `array_has` https://github.com/apache/arrow-datafusion/issues/6977

### Form an array:
- [x] `array_repeat` https://github.com/apache/arrow-datafusion/issues/7197
- [x] `array_resize` https://github.com/apache/arrow-datafusion/issues/7194

### Array aggregate functions:
- [ ] https://github.com/apache/arrow-datafusion/issues/7213
- [ ] https://github.com/apache/arrow-datafusion/issues/7214
### Array operators:
- [ ] https://github.com/apache/arrow-datafusion/issues/7119

### Handling `NULL` and empty array:
- [ ] https://github.com/apache/arrow-datafusion/issues/7143
- [ ] https://github.com/apache/arrow-datafusion/issues/7142
- [ ] https://github.com/apache/arrow-datafusion/issues/7144
- [x] https://github.com/apache/arrow-datafusion/issues/7136
- [x] https://github.com/apache/arrow-datafusion/issues/7290

### Refactoring:
- [x] https://github.com/apache/arrow-datafusion/issues/7279
- [x] https://github.com/apache/arrow-datafusion/issues/7288

### Other functions:
- [x] https://github.com/apache/arrow-datafusion/issues/7289
- [x] https://github.com/apache/arrow-datafusion/issues/8028

### Bugs
- [x] https://github.com/apache/arrow-datafusion/issues/8032

**Comment by jayzhan211** [comment]
Since there is array_intersect and array_except, did you find any function similar to array_union, the function that returns a list of all elements that exist in `one of the l1 and l2` without duplicates? list_intersect([1,2,3], [3,4,5]) -> [1,2,3,4,5]. It seems to me a helpful set operation, but not sure why Duckdb does not have this one.

**Comment by jayzhan211** [comment]
Should we accept nested arrays for `array_has_all` and array_has_any`, unlike `array_has` the rhs could be `array` not `element`.

**Comment by jayzhan211** [comment]
I will work on three of `array_has`

**Comment by jayzhan211** [comment]
I would like to try on `array_aggregate`. https://duckdb.org/docs/sql/functions/nested#list-aggregates
There are many kinds of rewrite functions, but most of them are not supported yet. I think we can start with the easy one or an existing function, like `sum`, `min`, or `max`.

**Comment by jayzhan211** [comment]
@izveigor , I dont fully understand about the difference between `list_xxx` and `array_xxx` in duckdb. As you said, list is for mutable, and array is for immutable. But like `append` a mutable function, why do they have `array_append`? `contains` a immutable function, but they have `list_contains`.  For aggregate rewrite functions like `list_min`, `list_sum`, they don't alias with array, no `array_min` or `array_sum`, but we can do the same things with `array_aggregate()`. 

How do we differentiate `list`, and `array` in datafusion?

**Comment by jayzhan211** [comment]
> > I would like to try on `array_aggregate`. https://duckdb.org/docs/sql/functions/nested#list-aggregates There are many kinds of rewrite functions, but most of them are not supported yet. I think we can start with the easy one or an existing function, like `sum`, `min`, or `max`.
> 
> It sounds great! Thank you, @jayzhan211! I created the tickets about this topic: #7213 and #7214.
> 
> > @izveigor , I dont fully understand about the difference between `list_xxx` and `array_xxx` in duckdb. As you said, list is for mutable, and array is for immutable. But like `append` a mutable function, why do they have `array_append`? `contains` a immutable function, but they have `list_contains`. For aggregate rewrite functions like `list_min`, `list_sum`, they don't alias with array, no `array_min` or `array_sum`, but we can do the same things with `array_aggregate()`.
> > How do we differentiate `list`, and `array` in datafusion?
> 
> I don't fully understand DuckDB principles myself. In my opinion every function should have `list_` and `array_` prefix due to the habit of using a single word. About mutability, this is purely my assumption of separation of functions, we may not adhere to it.

I asked someone that is familiar with duckdb, he says the reason that they have list_xxx and array_xxx is due to compatibility, postgres for array_xxx, and others for list_xxx. In this case, since we heavily adopted from duckdb, clickhouse and others, we should also use similar naming from them, but I don't think mutability is the thing that differentiates list_xxx and array_xxx, it might be misleading if we said that.

**Comment by alamb** [comment]
> I asked someone that is familiar with duckdb, he says the reason that they have list_xxx and array_xxx is due to compatibility, postgres for array_xxx, and others for list_xxx.

This would be great to add to the documentation if you had a chance -- thank you for the research @jayzhan211

**Comment by edmondop** [comment]
Can I pick something @jiangzhx that nobody else is looking to?

**Comment by alamb** [comment]
@izveigor  -- thank you for letting us know and for all your work so far in this project. I think it has driven DataFusion significantly and we have all benefited from your work and inspiration.

Good luck with your next adventure.

**Comment by jayzhan211** [comment]
TODO:
- #7194 `array_resize`
- #7142 / #7143 Null / Empty Handling
- #7213 / #7214 `array aggregate`
- #6555 `unnest`
- Struct / Fixed Size List / Large List ?

**Comment by Weijun-H** [comment]
#9021 support list_reverse in array

**Comment by alamb** [comment]
This looks pretty good to me now, I think we have done all the major items so closing this epic as good. We can handle small cleanup items as normal tickets. Please let me know if you disagree
