### ISSUE TITLE
[EPIC] Full support `wasm32-unknown-unknown` target (aka web assembly)

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#7651]
### Is your feature request related to a problem or challenge?

There are several projects that compile parts of DataFusion to WASM / web assembly via the `wasm32-unknown-unknown`

@jonmmease has added a CI check that the basics of WASM work with DataFusion in https://github.com/apache/arrow-datafusion/pull/7633. This ticket tracks additional work for improving WASM support

### Describe the solution you'd like
- [ ] https://github.com/apache/arrow-datafusion/issues/7652
- [x] https://github.com/apache/arrow-datafusion/issues/2042
- [x] https://github.com/apache/arrow-datafusion/issues/7653

**Comment by alamb** [comment]
I have made a new epic to track additional WASM improvements here:
- https://github.com/apache/datafusion/issues/13815
