### ISSUE TITLE
[EPIC] Tracking issue of support substrait logical plan

### ISSUE THREAD

**Issue by waynexia** [apache/datafusion#8149]
### Is your feature request related to a problem or challenge?

Tracks [substrait](https://substrait.io/) support progress

The rough goal of this ticket is:
- Support all basic operations that datafusion supports. I.e., reach the same coverage and functionalities as `datafusion-proto`
- Can co-operate with one or two external systems, like `spark-substrait`.

### LogicalPlan

- [x] CrossJoin https://github.com/apache/arrow-datafusion/pull/8427
- [x] Repartition https://github.com/apache/arrow-datafusion/pull/8526
- [ ] Subquery 
- [x] Values & EmptyRelation https://github.com/apache/datafusion/pull/10531
- [ ] Unnest

The following logical plans I think we don't need to support:

- Statement
- Analyze
- Explain
- Prepare
- Dml
- Ddl
- Copy
- DescribeTable

### Expression

- [x] Negative https://github.com/apache/arrow-datafusion/pull/8534
- [ ] SimilarTo
- [x] Not https://github.com/apache/arrow-datafusion/pull/8534
- [x] IsTrue https://github.com/apache/arrow-datafusion/pull/8534
- [x] IsFalse https://github.com/apache/arrow-datafusion/pull/8534
- [x] IsUnknown https://github.com/apache/arrow-datafusion/pull/8534
- [x] IsNotTrue https://github.com/apache/arrow-datafusion/pull/8534
- [x] IsNotFalse https://github.com/apache/arrow-datafusion/pull/8534
- [x] IsNotUnknown https://github.com/apache/arrow-datafusion/pull/8534
- [ ] TryCast
- [ ] Sort
- [ ] ScalarUDF
- [ ] Wildcard
- [ ] Exists
- [ ] GetIndexedField
- [x] InSubquery https://github.com/apache/arrow-datafusion/issues/8362
- [ ] ScalarSubquery
- [ ] Alias https://github.com/apache/arrow-datafusion/issues/6489

The following exprs I think we don't need to support:

- OuterReferenceColumn
- Placeholder

### Types and scalar
- [x] Interval (YearMonth, DayTime, MonthDayNano) https://github.com/apache/datafusion/pull/10646
- [x] Struct https://github.com/apache/datafusion/pull/10622
- [ ] Duration (Second, Milli, Micro, Nano)
- [ ] View (Binary, List, UTF-8, LargeList)
- [ ] Map
- [ ] REE
- [ ] Time32, Time64
- [ ] Union

### Meet the spec
- [ ] Define *.yaml for datafusion-specific extensions
- [ ] Provide URL for extension types
- [x] Support compound signature with function names https://github.com/apache/datafusion/pull/10653

### Test
- [ ] Pair test with external systems https://github.com/apache/datafusion/issues/10710

### Others
 
Things that need further verification:
- [ ] Case-sensitivity for both consumer and producer

### Additional context

Substrait to DataFusion's physical plan is tracked at https://github.com/apache/arrow-datafusion/issues/5173

**Comment by Blizzara** [comment]
Values (and EmptyTable) is supported as of #10531 :)

**Comment by waynexia** [comment]
> Values (and EmptyTable) is supported as of #10531 :)

Updated. Thanks for implementing it!

**Comment by ViggoC** [comment]
@waynexia Why do you think that we don't need to support OuterReferenceColumn? IMHO, It is the key path to implementing subquery.

**Comment by alamb** [comment]
I consolidated the outstanding substrait work in a new epic, so let's close this one and continue discussion there
 - https://github.com/apache/datafusion/issues/17159
