### ISSUE TITLE
Support `LargeList` for array

### ISSUE THREAD

**Issue by Weijun-H** [apache/datafusion#8185]
### Is your feature request related to a problem or challenge?

The array function currently does not support `LargeList`, and this ticket is to track its progress.
- [x] `array_length` #8121
- [x] `array_element` #8570
- [x] `array_slice` #8561
- [x] `array_pop_back` #8569
- [x] `array_pop_front` #8569
- [x] `array_prepend` #8679
- [x] `array_append` #8679
- [x] `array_empty` #8321
- [x] `array_repeat` #8725
- [x] `array_position` #8714 
- [x] `array_positions` #8571
- [x] `array_replace`, `array_replace_n`, `array_replace_all` #8595
- [x] `cardinality` #8726 
- [x] `array_dims` #8592 
- [x] `array_ndims` #8716
- [x] `array_has`, `array_has_any`, `array_has_all` #8322 
- [x] `array_intersect` #8516 
- [x] `array_to_string` #8729 
- [x] `flatten` #9110 

### Describe the solution you'd like

Use `OffsizeTrait` to refactor the current implementation

### Additional context

#8084

**Comment by Jefffrey** [comment]
I plan to go through the array functions in datafusion-functions-nested and check this support as well as tests

**Comment by Jefffrey** [comment]
- [x] [`array_has`, `array_has_all`, `array_has_any`][array_has.rs]
- [x] [`cardinality`][cardinality.rs] supports LargeList & FixedSizeList with accompanying SLT tests
- [x] [`array_prepend`, `array_append`, `array_concat`][concat.rs]
  - Adding more tests via #17672
- [x] [`array_dims`, `array_ndims`][dimension.rs] support LargeList & FixedSizeList with accompanying SLT tests
- [x] [`array_distance`][distance.rs] supports LargeList & FixedSizeList with accompanying SLT tests
- [x] [`array_empty`][empty.rs] supports LargeList & FixedSizeList with accompanying SLT tests
- [x] [`array_except`][except.rs] - See #17658 which adds FixedSizeList support & tests for LargeList
- [x] [`array_element`, `array_pop_front`, `array_pop_back`, `array_any_value`, `array_slice`][extract.rs] - See #17667 which adds FixedSizeList support for `array_slice` (rest are fine)
- [x] [`flatten`][flatten.rs]
- [x] [`array_length`][length.rs]
- [x] [`array_min`, `array_max`][min_max.rs]
  - Adding more tests via #17672
- [x] [`array_position`, `array_positions`][position.rs] - See #17659 which adds FixedSizeList support
- [x] [`array_remove`, `array_remove_n`, `array_remove_all`][remove.rs]
- [x] [`array_replace`, `array_replace_n`, `array_replace_all`][replace.rs]
  - Adding more tests via #17672
- [x] [`array_resize`][resize.rs]
  - Adding more tests via #17672
- [x] [`array_reverse`][reverse.rs]
- [x] [`array_union`, `array_intersect`, `array_distinct`][set_ops.rs]
  - Adding more tests via #17672
- [x] [`array_sort`][sort.rs] - See #17657 which adds LargeList support & tests for FixedSizeList
- [x] [`array_to_string`][string.rs] - See #17666 which adds FixedSizeList support

[array_has.rs]: https://github.com/apache/datafusion/blob/d587b8d3b7a0c0e943055de7576a06c45a383388/datafusion/functions-nested/src/array_has.rs
[cardinality.rs]: https://github.com/apache/datafusion/blob/d587b8d3b7a0c0e943055de7576a06c45a383388/datafusion/functions-nested/src/cardinality.rs
[concat.rs]: https://github.com/apache/datafusion/blob/d587b8d3b7a0c0e943055de7576a06c45a383388/datafusion/functions-nested/src/concat.rs
[dimension.rs]: https://github.com/apache/datafusion/blob/d587b8d3b7a0c0e943055de7576a06c45a383388/datafusion/functions-nested/src/dimension.rs
[distance.rs]: https://github.com/apache/datafusion/blob/d587b8d3b7a0c0e943055de7576a06c45a383388/datafusion/functions-nested/src/distance.rs
[empty.rs]: https://github.com/apache/datafusion/blob/d587b8d3b7a0c0e943055de7576a06c45a383388/datafusion/functions-nested/src/empty.rs
[except.rs]: https://github.com/apache/datafusion/blob/d587b8d3b7a0c0e943055de7576a06c45a383388/datafusion/functions-nested/src/except.rs
[extract.rs]: https://github.com/apache/datafusion/blob/d587b8d3b7a0c0e943055de7576a06c45a383388/datafusion/functions-nested/src/extract.rs
[flatten.rs]: https://github.com/apache/datafusion/blob/d587b8d3b7a0c0e943055de7576a06c45a383388/datafusion/functions-nested/src/flatten.rs
[length.rs]: https://github.com/apache/datafusion/blob/d587b8d3b7a0c0e943055de7576a06c45a383388/datafusion/functions-nested/src/length.rs
[min_max.rs]: https://github.com/apache/datafusion/blob/d587b8d3b7a0c0e943055de7576a06c45a383388/datafusion/functions-nested/src/min_max.rs
[position.rs]: https://github.com/apache/datafusion/blob/d587b8d3b7a0c0e943055de7576a06c45a383388/datafusion/functions-nested/src/position.rs
[remove.rs]: https://github.com/apache/datafusion/blob/d587b8d3b7a0c0e943055de7576a06c45a383388/datafusion/functions-nested/src/remove.rs
[replace.rs]: https://github.com/apache/datafusion/blob/d587b8d3b7a0c0e943055de7576a06c45a383388/datafusion/functions-nested/src/replace.rs
[resize.rs]: https://github.com/apache/datafusion/blob/d587b8d3b7a0c0e943055de7576a06c45a383388/datafusion/functions-nested/src/resize.rs
[reverse.rs]: https://github.com/apache/datafusion/blob/d587b8d3b7a0c0e943055de7576a06c45a383388/datafusion/functions-nested/src/reverse.rs
[set_ops.rs]: https://github.com/apache/datafusion/blob/d587b8d3b7a0c0e943055de7576a06c45a383388/datafusion/functions-nested/src/set_ops.rs
[sort.rs]: https://github.com/apache/datafusion/blob/d587b8d3b7a0c0e943055de7576a06c45a383388/datafusion/functions-nested/src/sort.rs
[string.rs]: https://github.com/apache/datafusion/blob/d587b8d3b7a0c0e943055de7576a06c45a383388/datafusion/functions-nested/src/string.rs

**Comment by Jefffrey** [comment]
I'll close this as done as per my check above it seems all array functions accept LargeLists and FixedSizeLists now
