### ISSUE TITLE
[Epic] A collection of Join Improvements

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#8398]
This ticket gathers various join related potential improvements in DataFusion:

- [ ] https://github.com/apache/arrow-datafusion/issues/318
- [ ] https://github.com/apache/arrow-datafusion/issues/8273
- [x] https://github.com/apache/arrow-datafusion/issues/8393
- [ ] https://github.com/apache/arrow-datafusion/issues/7955
- [x] https://github.com/apache/arrow-datafusion/issues/7848
- [x] https://github.com/apache/arrow-datafusion/issues/6768

Bugs
- [x] https://github.com/apache/arrow-datafusion/issues/8374
- [x] https://github.com/apache/arrow-datafusion/issues/7931
- [ ] https://github.com/apache/arrow-datafusion/issues/7394
- [x] https://github.com/apache/arrow-datafusion/issues/6744
