### ISSUE TITLE
[Epic] Port BuiltInFunctons to `datafusion-functions-*` crates

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#9285]
### Is your feature request related to a problem or challenge?

As part of making DataFusion even more customizable (https://github.com/apache/arrow-datafusion/issues/8045), it is valuable to let system designers mix and match different packages of functions to get the precise behavior they want (e.g. postgres style `to_date` or spark style `to_date`).

To support this functionality as well as  to ensure the `ScalarUDF` API exposes the full power of DataFusion, we are in the process of extracting the "built in" functions out of the core and into separate crates.

This epic tracks the work to actually move the functions out of the core datafusion crate (spread through `datafusion_expr` and `datafusion-physical-expr` and into the new `datafusion-functions` / `datafusion-functions-array` crates

### Tasks:

Here is list of many of the items necessary to complete this transition. Eventually there should be tickets for all tasks, and there are tickets for some already, but I don't want to make 100s of tickets all at once. I plan to make more as we make it through more of this project.

Anyone should feel free to make other tickets if they want to help with items below.

# `math_expressions`
These should be located in the `datafusion-functions` crate ([source link](https://github.com/apache/arrow-datafusion/blob/main/datafusion/functions))
Code location: https://github.com/apache/arrow-datafusion/blob/main/datafusion/functions/src/math/mod.rs
- [x] https://github.com/apache/arrow-datafusion/pull/9216
- [x] https://github.com/apache/arrow-datafusion/issues/9286
- [x] https://github.com/apache/arrow-datafusion/pull/9297
- [x] Abs, Asin,
- [x] Atan, Atan2, Acosh, Asinh, Atanh,
- [x] Cbrt, Ceil, Cos, Cosh, Degrees
- [ ] Exp, Factorial https://github.com/apache/arrow-datafusion/issues/9939
- [x] Floor, Gcd, Lcm, Ln, Log, Log10, Log2, Pi, Power,
- [x] Radians, Signum, Sin, Sinh, Sqrt,
- [x] Tan, Tanh, Trunc, Cot, Round, iszero

## `array_expressions`
Note that given the size and specialization of these functions are put in their own subcrate, [`datafusion-functions-array`](https://github.com/apache/arrow-datafusion/blob/main/datafusion/functions-array)

- ArrayToString https://github.com/apache/arrow-datafusion/pull/9113
- ArrayDims, ArrayNdims, Cardinality https://github.com/apache/arrow-datafusion/pull/9425
- ArrayHas, ArrayHasAll, ArrayHasAny https://github.com/apache/arrow-datafusion/pull/9496
- MakeArray, ArrayAppend, ArrayPrepend, ArrayConat https://github.com/apache/arrow-datafusion/pull/9343 https://github.com/apache/arrow-datafusion/issues/9288 #9504 
- Range, GenSeries #9352
- ArrayEmpty ArrayLength #9510 
- Flatten #9523 
- StringToArray #9497
- ArraySort #9551
- ArrayDistinct #9549 
- ArrayRepeat #9565
- ArrayResize #9570
- ArrayElement, ArraySlice, ArrayPopFront, ArrayPopBack #9615
- ArrayPosition, ArrayPositions #9617
- ArrayReverse #9630
- ArrayIntersect, ArrayUnion #9629
- ArrayExcept #9634 
- ArrayRemove, ArrayRemoveN, ArrayRemoveAll #9635 
- ArrayReplace, ArrayReplaceN, ArrayReplaceAll #9651
- [X] `MakeArray`:  construct an array from columns (union/except depends on this)
- [x] https://github.com/apache/arrow-datafusion/issues/9519

## Core functions
These should be located in the `datafusion-functions` crate ([source link](https://github.com/apache/arrow-datafusion/blob/main/datafusion/functions))
Code location: https://github.com/apache/arrow-datafusion/blob/main/datafusion/functions/src/core/mod.rs

- [x] Create `core` module, extract `nullif`: https://github.com/apache/arrow-datafusion/pull/9216
- [x] https://github.com/apache/arrow-datafusion/issues/9287
- [x] Move `ArrowTypeOf`: return the arrow type of a value #9524 
- [ ] `Coalesce`: return the first non-null value
- [ ] `Struct`: Create a struct
- [ ] `NullIf`: return null if the two values are equal
- [ ] `Random`: return a random number
- [ ] `Nanvl`: return the first non-NaN value

## `crypto_expressions`
These should be located in the `datafusion-functions` crate ([source link](https://github.com/apache/arrow-datafusion/blob/main/datafusion/functions))
Code location: https://github.com/apache/arrow-datafusion/blob/main/datafusion/functions/src/crypto/mod.rs

- [ ] Create `crypto` module in `datafusion/functions/src/crypto` and `crypto_expressions` feature flag, move `digest` function
- [ ] Digest, MD5, SHA224, SHA256, SHA384, SHA512

## `string_expressions`
These should be located in the `datafusion-functions` crate ([source link](https://github.com/apache/arrow-datafusion/blob/main/datafusion/functions))
Code location: https://github.com/apache/arrow-datafusion/blob/main/datafusion/functions/src/string/mod.rs

- concat, concat_ws, ends_with, initcap #9540 
- [ ] Create `string` module in  `datafusion/functions/src/string` and `string_expressions` feature flag, move `ascii` function
- [ ] ascii, bit_length, btrim, chr,
- [ ] instr, lower, ltrim, octet_length,
- [ ] repeat, replace, rtrim, split_part,
- [ ] starts_with, to_hex, trim, upper,
- [ ] levenshtein, uuid, overlay

## `unicode_expressions`
These should be located in the `datafusion-functions` crate ([source link](https://github.com/apache/arrow-datafusion/blob/main/datafusion/functions))
Code location: https://github.com/apache/arrow-datafusion/blob/main/datafusion/functions/src/unicode/mod.rs

- [ ] Create `unicode` module in  `datafusion/functions/src/unicode` and `unicode_expressions` feature flag, move `charlength` function
- [ ] CharLength,
- [ ] Left, Lpad, Reverse, Right, Rpad,
- [ ] Strpos, Substr,
- [ ] Translate, SubstrIndex, FindInSet

## `regex_expressions`
These should be located in the `datafusion-functions` crate ([source link](https://github.com/apache/arrow-datafusion/blob/main/datafusion/functions))
Code location: https://github.com/apache/arrow-datafusion/blob/main/datafusion/functions/src/regexp/mod.rs

- [x] https://github.com/apache/arrow-datafusion/issues/9328
- [ ] RegexpMatch, RegexpReplace
- [ ] RegexpLike

## `datetime_expressions`
These should be located in the `datafusion-functions` crate ([source link](https://github.com/apache/arrow-datafusion/blob/main/datafusion/functions))
Code location: https://github.com/apache/arrow-datafusion/blob/main/datafusion/functions/src/datetime/mod.rs

- [ ] Create `datetime` module in `datafusion/functions/src/datetime` and `datetime_expressions` feature flag, move `date_part`
- [x] https://github.com/apache/arrow-datafusion/issues/9291
- [ ] port benchmarks to datafusion-functions crate
- [ ] date_part, date_trunc, date_bin,
- [ ] to_timestamp, to_timestamp_millis, to_timestamp_micros, to_timestamp_nanos, to_timestamp_seconds,
- [ ] from_unixtime, now, current_date, current_time

## Infrastructure
- [x] https://github.com/apache/arrow-datafusion/issues/9289

### Additional context

The organization was discussed in https://github.com/apache/arrow-datafusion/issues/9100

**Comment by SteveLauC** [comment]
Let me give this a try:

>## `math_expressions`
>
>  [ ] Abs, Acos, Asin,

**Comment by Lordworms** [comment]
I'll try to do regex_expressions parts.

**Comment by guojidan** [comment]
I'll try to do array_expressions parts.

**Comment by yyy1000** [comment]
I filed #9336 which I think may be necessary before we port functions.

**Comment by guojidan** [comment]
> work on `array_concat`

hi @jayzhan211 I already work on `array_concat` #9343

**Comment by jayzhan211** [comment]
Oh, sorry. I will work on other

**Comment by jayzhan211** [comment]
Take ArrayHas, ArrayHasAll, ArrayHasAny

**Comment by SteveLauC** [comment]
Take Atan, Atan2, Acosh.

**Comment by Weijun-H** [comment]
Take ArrayPopFront, ArrayPopBack, ArrayDims, ArrayDistinct, ArrayElement

**Comment by Weijun-H** [comment]
Take ArrayDims, ArrayNdims, Cardinality

**Comment by jayzhan211** [comment]
> Take ArrayHas, ArrayHasAll, ArrayHasAny

I think this needs to wait until `make_array` is done and also move to rewrite to the optimizer.

Take ArrayIntersect, ArrayUnion, ArrayExcept

**Comment by jayzhan211** [comment]
While I worked on ArrayElement, I found that `GetFieldAccessExpr::ListIndex` uses `array_element` in physical-expr https://github.com/apache/arrow-datafusion/blob/581fd98270e69221689ddd4c37566ef620a67167/datafusion/physical-expr/src/expressions/get_indexed_field.rs#L252-L257 ListRange likewise, which is kernel function in `function-arrays` crate, instead of converting ArrayRef to Expr, I'm thinking of making array function kernel public. @alamb Do you think we can make those array functions public? And, is importing `function-arrays` to crate `physical-expr` a concern like crate `optimize` is?

If neither is a good idea, we may need to rewrite ListIndex and ListRange to array function early.

**Comment by alamb** [comment]
> ListRange likewise, which is kernel function in `function-arrays` crate, instead of converting ArrayRef to Expr, I'm thinking of making array function kernel public. @alamb Do you think we can make those array functions public? And, is importing `function-arrays` to crate `physical-expr` a concern like crate `optimize` is?

I think making physical-exprs depend on datafusion-functions would be unfortunate (as it would still mean there could be dependencies / special cases from built in functions to "built in" user defined functions)

> If neither is a good idea, we may need to rewrite ListIndex and ListRange to array function early.

I agree if this is possible it would be the best approach from my perspective

I also though about about potentially adding the common code to the new `datafusion_common_runtime` crate (that @mustafasrepo  added recently) 

https://github.com/apache/arrow-datafusion/tree/main/datafusion/common_runtime

But I think that would result in a tokio dependency on datafusion-functions which would be unwise.

**Comment by Omega359** [comment]
> I think making physical-exprs depend on datafusion-functions would be unfortunate (as it would still mean there could be dependencies / special cases from built in functions to "built in" user defined functions)
> 
> > If neither is a good idea, we may need to rewrite ListIndex and ListRange to array function early.
> 
> I agree if this is possible it would be the best approach from my perspective

Hmm. I had the same issue with datebin being referenced in physical-expr - though only for a test which likely could be moved elsewhere or somehow adjusted in some other way. The [draft pr](https://github.com/apache/arrow-datafusion/pull/9435) in fact does just replace it with the moved datebin and thus does import the functions crate. I'll look at updating those tests in some way to remove that dependency.

I also encountered function [references ](https://github.com/apache/arrow-datafusion/blob/a84e5f89bd52d59c78f11fffbab89ed1d418538f/datafusion/sql/src/expr/mod.rs#L173) in the sql crate that I really can't see a way to work around unless we somehow allow SQLExpr to be a part of a ScalarUdf or similar.

**Comment by alamb** [comment]
> I also encountered function [references ](https://github.com/apache/arrow-datafusion/blob/a84e5f89bd52d59c78f11fffbab89ed1d418538f/datafusion/sql/src/expr/mod.rs#L173)in the sql crate that I really can't see a way to work around unless we somehow allow SQLExpr to be a part of a ScalarUdf or similar.

I was thinking in the sql parser we can just switch to lookung up functions by name (and the sql planner already has a function registry)

> Hmm. I had the same issue with datebin being referenced in physical-expr 

Perhaps it is time to make a new crate that contains common function implementation code 🤔

**Comment by Lordworms** [comment]
Take crypto parts

**Comment by Weijun-H** [comment]
Take ArrayEmpty and ArrayLength

**Comment by Weijun-H** [comment]
Take Flatten

**Comment by yyy1000** [comment]
Take ArrowTypeOf

**Comment by ongchi** [comment]
Take Tan, Tanh

**Comment by PsiACE** [comment]
take string module  and ascii, bit_length, btrim, chr

**Comment by Tangruilin** [comment]
take string module starts_with, to_hex, trim, upper

**Comment by Tangruilin** [comment]
take concat, concat_ws, ends_with, initcap,

**Comment by yyy1000** [comment]
take Struct in Core

**Comment by erenavsarogullari** [comment]
`ArraySort` and `ArrayDistinct` are also being addressed by following PRs: https://github.com/apache/arrow-datafusion/pull/9551 and https://github.com/apache/arrow-datafusion/pull/9549 so they can also be reflected to above table. Thanks.

**Comment by jayzhan211** [comment]
@erenavsarogullari I think it is fine to split function to other file to avoid crazy conflict.

**Comment by erenavsarogullari** [comment]
@jayzhan211 Thanks for notification. Yes, makes sense. We can define new `udf` definitions as separate file (single func per file). WDYT on `datafusion/functions-array/src/kernels.rs`? (Its size also increases)

**Comment by jayzhan211** [comment]
> WDYT on `datafusion/functions-array/src/kernels.rs` (Its size also increases)?
let's move them out too!

**Comment by jayzhan211** [comment]
Take `pop_front` and `pop_back`, they need to be moved together with slice

**Comment by Weijun-H** [comment]
Take `ArrayReverse`

**Comment by erenavsarogullari** [comment]
`ArrayExcept`: PR(#9634) has been submitted
`ArrayRemove`, `ArrayRemoveN`, `ArrayRemoveAll`: Work in Progress(#9635)

**Comment by Weijun-H** [comment]
take array_remove family

**Comment by erenavsarogullari** [comment]
@jayzhan211, Just follow-up to our previous discussion (single func per file), we almost complete `functions-array` migration. Its `kernels` and `udf` source files include more functions by our new pattern. Does it make sense to break them as well by aligning the new pattern and consistency?

**Comment by jayzhan211** [comment]
It makes sense to me 👍

**Comment by jayzhan211** [comment]
@erenavsarogullari
For consistency, I think we can also change the `invoke` with `make_scalar_function` (probably a better name). It returns ColumnValue::Scalar if length of list is 1. It has no difference currently, since we have no optimization based on Scalar.

**Comment by erenavsarogullari** [comment]
@jayzhan211 Yes, makes sense. I have created #9660 for this refactoring. I will also include to be used `make_scalar_function` for `invoke` calls.

**Comment by tinfoil-knight** [comment]
Take Ln, Log, Log10, Log2

**Comment by Omega359** [comment]
Take lower, ltrim, octet_length

**Comment by Omega359** [comment]
take levenshtein, uuid, overlay

**Comment by Weijun-H** [comment]
take Atan, Acosh, Asinh, Atanh,
